// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Iwahbe.Resend
{
    /// <summary>
    /// A Resend custom contact property definition.
    /// </summary>
    [ResendResourceType("resend:index:ContactProperty")]
    public partial class ContactProperty : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The timestamp when Resend created the contact property, as returned by the Resend API `created_at` string.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
        /// </summary>
        [Output("fallbackValue")]
        public Output<object?> FallbackValue { get; private set; } = null!;

        /// <summary>
        /// The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
        /// </summary>
        [Output("type")]
        public Output<Iwahbe.Resend.ContactPropertyType> Type { get; private set; } = null!;


        /// <summary>
        /// Create a ContactProperty resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ContactProperty(string name, ContactPropertyArgs args, CustomResourceOptions? options = null)
            : base("resend:index:ContactProperty", name, args ?? new ContactPropertyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ContactProperty(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("resend:index:ContactProperty", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/iwahbe/pulumi-resend",
                ReplaceOnChanges =
                {
                    "key",
                    "type",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ContactProperty resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ContactProperty Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ContactProperty(name, id, options);
        }
    }

    public sealed class ContactPropertyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
        /// </summary>
        [Input("fallbackValue")]
        public Input<object>? FallbackValue { get; set; }

        /// <summary>
        /// The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
        /// </summary>
        [Input("type", required: true)]
        public Input<Iwahbe.Resend.ContactPropertyType> Type { get; set; } = null!;

        public ContactPropertyArgs()
        {
        }
        public static new ContactPropertyArgs Empty => new ContactPropertyArgs();
    }
}
