// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Iwahbe.Resend
{
    /// <summary>
    /// Triggers verification of a Resend domain and waits until the domain's DNS records have been verified. Create this resource after the domain's DNS records (from the `Domain` resource's `records` output) have been published.
    /// </summary>
    [ResendResourceType("resend:index:DomainVerification")]
    public partial class DomainVerification : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The ID of the domain to verify.
        /// </summary>
        [Output("domainId")]
        public Output<string> DomainId { get; private set; } = null!;

        /// <summary>
        /// The verification status of the domain.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// How long to wait for verification before failing. Defaults to 900 seconds.
        /// </summary>
        [Output("timeoutSeconds")]
        public Output<int?> TimeoutSeconds { get; private set; } = null!;


        /// <summary>
        /// Create a DomainVerification resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DomainVerification(string name, DomainVerificationArgs args, CustomResourceOptions? options = null)
            : base("resend:index:DomainVerification", name, args ?? new DomainVerificationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DomainVerification(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("resend:index:DomainVerification", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/iwahbe/pulumi-resend",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DomainVerification resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DomainVerification Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new DomainVerification(name, id, options);
        }
    }

    public sealed class DomainVerificationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the domain to verify.
        /// </summary>
        [Input("domainId", required: true)]
        public Input<string> DomainId { get; set; } = null!;

        /// <summary>
        /// How long to wait for verification before failing. Defaults to 900 seconds.
        /// </summary>
        [Input("timeoutSeconds")]
        public Input<int>? TimeoutSeconds { get; set; }

        public DomainVerificationArgs()
        {
        }
        public static new DomainVerificationArgs Empty => new DomainVerificationArgs();
    }
}
