// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Iwahbe.Resend
{
    /// <summary>
    /// A domain registered with Resend for sending (and optionally receiving) email. The `records` output contains the DNS records that must be created before the domain can be verified.
    /// </summary>
    [ResendResourceType("resend:index:Domain")]
    public partial class Domain : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Enable `sending` and/or `receiving` for this domain.
        /// </summary>
        [Output("capabilities")]
        public Output<Outputs.DomainCapabilities?> Capabilities { get; private set; } = null!;

        /// <summary>
        /// Track link clicks in HTML emails. Requires a verified tracking subdomain.
        /// </summary>
        [Output("clickTracking")]
        public Output<bool?> ClickTracking { get; private set; } = null!;

        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The subdomain used for the Return-Path address. Defaults to `send`.
        /// </summary>
        [Output("customReturnPath")]
        public Output<string?> CustomReturnPath { get; private set; } = null!;

        /// <summary>
        /// The domain name, e.g. `example.com`.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Track email open rates. Requires a verified tracking subdomain.
        /// </summary>
        [Output("openTracking")]
        public Output<bool?> OpenTracking { get; private set; } = null!;

        /// <summary>
        /// The DNS records to create for this domain.
        /// </summary>
        [Output("records")]
        public Output<ImmutableArray<Outputs.DomainRecord>> Records { get; private set; } = null!;

        /// <summary>
        /// The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
        /// </summary>
        [Output("region")]
        public Output<Iwahbe.Resend.DomainRegion?> Region { get; private set; } = null!;

        /// <summary>
        /// The verification status of the domain.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// Connection encryption: `opportunistic` (default) or `enforced`.
        /// </summary>
        [Output("tls")]
        public Output<Iwahbe.Resend.DomainTLS?> Tls { get; private set; } = null!;

        /// <summary>
        /// Custom subdomain used for open/click tracking links.
        /// </summary>
        [Output("trackingSubdomain")]
        public Output<string?> TrackingSubdomain { get; private set; } = null!;


        /// <summary>
        /// Create a Domain resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Domain(string name, DomainArgs args, CustomResourceOptions? options = null)
            : base("resend:index:Domain", name, args ?? new DomainArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Domain(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("resend:index:Domain", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/iwahbe/pulumi-resend",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Domain resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Domain Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Domain(name, id, options);
        }
    }

    public sealed class DomainArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable `sending` and/or `receiving` for this domain.
        /// </summary>
        [Input("capabilities")]
        public Input<Inputs.DomainCapabilitiesArgs>? Capabilities { get; set; }

        /// <summary>
        /// Track link clicks in HTML emails. Requires a verified tracking subdomain.
        /// </summary>
        [Input("clickTracking")]
        public Input<bool>? ClickTracking { get; set; }

        /// <summary>
        /// The subdomain used for the Return-Path address. Defaults to `send`.
        /// </summary>
        [Input("customReturnPath")]
        public Input<string>? CustomReturnPath { get; set; }

        /// <summary>
        /// The domain name, e.g. `example.com`.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Track email open rates. Requires a verified tracking subdomain.
        /// </summary>
        [Input("openTracking")]
        public Input<bool>? OpenTracking { get; set; }

        /// <summary>
        /// The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
        /// </summary>
        [Input("region")]
        public Input<Iwahbe.Resend.DomainRegion>? Region { get; set; }

        /// <summary>
        /// Connection encryption: `opportunistic` (default) or `enforced`.
        /// </summary>
        [Input("tls")]
        public Input<Iwahbe.Resend.DomainTLS>? Tls { get; set; }

        /// <summary>
        /// Custom subdomain used for open/click tracking links.
        /// </summary>
        [Input("trackingSubdomain")]
        public Input<string>? TrackingSubdomain { get; set; }

        public DomainArgs()
        {
        }
        public static new DomainArgs Empty => new DomainArgs();
    }
}
