// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Iwahbe.Resend
{
    [EnumType]
    public readonly struct ApiKeyPermission : IEquatable<ApiKeyPermission>
    {
        private readonly string _value;

        private ApiKeyPermission(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// Full access to the Resend API.
        /// </summary>
        public static ApiKeyPermission Full_access { get; } = new ApiKeyPermission("full_access");
        /// <summary>
        /// Permission to send emails.
        /// </summary>
        public static ApiKeyPermission Sending_access { get; } = new ApiKeyPermission("sending_access");

        public static bool operator ==(ApiKeyPermission left, ApiKeyPermission right) => left.Equals(right);
        public static bool operator !=(ApiKeyPermission left, ApiKeyPermission right) => !left.Equals(right);

        public static explicit operator string(ApiKeyPermission value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is ApiKeyPermission other && Equals(other);
        public bool Equals(ApiKeyPermission other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct DomainCapabilityStatus : IEquatable<DomainCapabilityStatus>
    {
        private readonly string _value;

        private DomainCapabilityStatus(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static DomainCapabilityStatus Enabled { get; } = new DomainCapabilityStatus("enabled");
        public static DomainCapabilityStatus Disabled { get; } = new DomainCapabilityStatus("disabled");

        public static bool operator ==(DomainCapabilityStatus left, DomainCapabilityStatus right) => left.Equals(right);
        public static bool operator !=(DomainCapabilityStatus left, DomainCapabilityStatus right) => !left.Equals(right);

        public static explicit operator string(DomainCapabilityStatus value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is DomainCapabilityStatus other && Equals(other);
        public bool Equals(DomainCapabilityStatus other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct DomainRegion : IEquatable<DomainRegion>
    {
        private readonly string _value;

        private DomainRegion(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static DomainRegion Us_east_1 { get; } = new DomainRegion("us-east-1");
        public static DomainRegion Eu_west_1 { get; } = new DomainRegion("eu-west-1");
        public static DomainRegion Sa_east_1 { get; } = new DomainRegion("sa-east-1");
        public static DomainRegion Ap_northeast_1 { get; } = new DomainRegion("ap-northeast-1");

        public static bool operator ==(DomainRegion left, DomainRegion right) => left.Equals(right);
        public static bool operator !=(DomainRegion left, DomainRegion right) => !left.Equals(right);

        public static explicit operator string(DomainRegion value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is DomainRegion other && Equals(other);
        public bool Equals(DomainRegion other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct DomainTLS : IEquatable<DomainTLS>
    {
        private readonly string _value;

        private DomainTLS(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static DomainTLS Enforced { get; } = new DomainTLS("enforced");
        public static DomainTLS Opportunistic { get; } = new DomainTLS("opportunistic");

        public static bool operator ==(DomainTLS left, DomainTLS right) => left.Equals(right);
        public static bool operator !=(DomainTLS left, DomainTLS right) => !left.Equals(right);

        public static explicit operator string(DomainTLS value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is DomainTLS other && Equals(other);
        public bool Equals(DomainTLS other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct WebhookEvent : IEquatable<WebhookEvent>
    {
        private readonly string _value;

        private WebhookEvent(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static WebhookEvent Email_sent { get; } = new WebhookEvent("email.sent");
        public static WebhookEvent Email_delivered { get; } = new WebhookEvent("email.delivered");
        public static WebhookEvent Email_delivery_delayed { get; } = new WebhookEvent("email.delivery_delayed");
        public static WebhookEvent Email_complained { get; } = new WebhookEvent("email.complained");
        public static WebhookEvent Email_bounced { get; } = new WebhookEvent("email.bounced");
        public static WebhookEvent Email_opened { get; } = new WebhookEvent("email.opened");
        public static WebhookEvent Email_clicked { get; } = new WebhookEvent("email.clicked");
        public static WebhookEvent Email_received { get; } = new WebhookEvent("email.received");
        public static WebhookEvent Email_failed { get; } = new WebhookEvent("email.failed");
        public static WebhookEvent Email_scheduled { get; } = new WebhookEvent("email.scheduled");
        public static WebhookEvent Email_suppressed { get; } = new WebhookEvent("email.suppressed");
        public static WebhookEvent Contact_created { get; } = new WebhookEvent("contact.created");
        public static WebhookEvent Contact_updated { get; } = new WebhookEvent("contact.updated");
        public static WebhookEvent Contact_deleted { get; } = new WebhookEvent("contact.deleted");
        public static WebhookEvent Domain_created { get; } = new WebhookEvent("domain.created");
        public static WebhookEvent Domain_updated { get; } = new WebhookEvent("domain.updated");
        public static WebhookEvent Domain_deleted { get; } = new WebhookEvent("domain.deleted");

        public static bool operator ==(WebhookEvent left, WebhookEvent right) => left.Equals(right);
        public static bool operator !=(WebhookEvent left, WebhookEvent right) => !left.Equals(right);

        public static explicit operator string(WebhookEvent value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is WebhookEvent other && Equals(other);
        public bool Equals(WebhookEvent other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
