// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resend

import (
	"context"
	"reflect"

	"errors"
	"github.com/iwahbe/pulumi-resend/sdk/go/resend/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Resend custom contact property definition.
type ContactProperty struct {
	pulumi.CustomResourceState

	// The timestamp when Resend created the contact property, as returned by the Resend API `created_at` string.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
	FallbackValue pulumi.AnyOutput `pulumi:"fallbackValue"`
	// The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
	Key pulumi.StringOutput `pulumi:"key"`
	// The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
	Type ContactPropertyTypeOutput `pulumi:"type"`
}

// NewContactProperty registers a new resource with the given unique name, arguments, and options.
func NewContactProperty(ctx *pulumi.Context,
	name string, args *ContactPropertyArgs, opts ...pulumi.ResourceOption) (*ContactProperty, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Key == nil {
		return nil, errors.New("invalid value for required argument 'Key'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"key",
		"type",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ContactProperty
	err := ctx.RegisterResource("resend:index:ContactProperty", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetContactProperty gets an existing ContactProperty resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetContactProperty(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ContactPropertyState, opts ...pulumi.ResourceOption) (*ContactProperty, error) {
	var resource ContactProperty
	err := ctx.ReadResource("resend:index:ContactProperty", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ContactProperty resources.
type contactPropertyState struct {
}

type ContactPropertyState struct {
}

func (ContactPropertyState) ElementType() reflect.Type {
	return reflect.TypeOf((*contactPropertyState)(nil)).Elem()
}

type contactPropertyArgs struct {
	// Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
	FallbackValue interface{} `pulumi:"fallbackValue"`
	// The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
	Key string `pulumi:"key"`
	// The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
	Type ContactPropertyType `pulumi:"type"`
}

// The set of arguments for constructing a ContactProperty resource.
type ContactPropertyArgs struct {
	// Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
	FallbackValue pulumi.Input
	// The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
	Key pulumi.StringInput
	// The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
	Type ContactPropertyTypeInput
}

func (ContactPropertyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*contactPropertyArgs)(nil)).Elem()
}

type ContactPropertyInput interface {
	pulumi.Input

	ToContactPropertyOutput() ContactPropertyOutput
	ToContactPropertyOutputWithContext(ctx context.Context) ContactPropertyOutput
}

func (*ContactProperty) ElementType() reflect.Type {
	return reflect.TypeOf((**ContactProperty)(nil)).Elem()
}

func (i *ContactProperty) ToContactPropertyOutput() ContactPropertyOutput {
	return i.ToContactPropertyOutputWithContext(context.Background())
}

func (i *ContactProperty) ToContactPropertyOutputWithContext(ctx context.Context) ContactPropertyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContactPropertyOutput)
}

// ContactPropertyArrayInput is an input type that accepts ContactPropertyArray and ContactPropertyArrayOutput values.
// You can construct a concrete instance of `ContactPropertyArrayInput` via:
//
//	ContactPropertyArray{ ContactPropertyArgs{...} }
type ContactPropertyArrayInput interface {
	pulumi.Input

	ToContactPropertyArrayOutput() ContactPropertyArrayOutput
	ToContactPropertyArrayOutputWithContext(context.Context) ContactPropertyArrayOutput
}

type ContactPropertyArray []ContactPropertyInput

func (ContactPropertyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ContactProperty)(nil)).Elem()
}

func (i ContactPropertyArray) ToContactPropertyArrayOutput() ContactPropertyArrayOutput {
	return i.ToContactPropertyArrayOutputWithContext(context.Background())
}

func (i ContactPropertyArray) ToContactPropertyArrayOutputWithContext(ctx context.Context) ContactPropertyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContactPropertyArrayOutput)
}

// ContactPropertyMapInput is an input type that accepts ContactPropertyMap and ContactPropertyMapOutput values.
// You can construct a concrete instance of `ContactPropertyMapInput` via:
//
//	ContactPropertyMap{ "key": ContactPropertyArgs{...} }
type ContactPropertyMapInput interface {
	pulumi.Input

	ToContactPropertyMapOutput() ContactPropertyMapOutput
	ToContactPropertyMapOutputWithContext(context.Context) ContactPropertyMapOutput
}

type ContactPropertyMap map[string]ContactPropertyInput

func (ContactPropertyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ContactProperty)(nil)).Elem()
}

func (i ContactPropertyMap) ToContactPropertyMapOutput() ContactPropertyMapOutput {
	return i.ToContactPropertyMapOutputWithContext(context.Background())
}

func (i ContactPropertyMap) ToContactPropertyMapOutputWithContext(ctx context.Context) ContactPropertyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContactPropertyMapOutput)
}

type ContactPropertyOutput struct{ *pulumi.OutputState }

func (ContactPropertyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ContactProperty)(nil)).Elem()
}

func (o ContactPropertyOutput) ToContactPropertyOutput() ContactPropertyOutput {
	return o
}

func (o ContactPropertyOutput) ToContactPropertyOutputWithContext(ctx context.Context) ContactPropertyOutput {
	return o
}

// The timestamp when Resend created the contact property, as returned by the Resend API `created_at` string.
func (o ContactPropertyOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ContactProperty) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
func (o ContactPropertyOutput) FallbackValue() pulumi.AnyOutput {
	return o.ApplyT(func(v *ContactProperty) pulumi.AnyOutput { return v.FallbackValue }).(pulumi.AnyOutput)
}

// The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
func (o ContactPropertyOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v *ContactProperty) pulumi.StringOutput { return v.Key }).(pulumi.StringOutput)
}

// The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
func (o ContactPropertyOutput) Type() ContactPropertyTypeOutput {
	return o.ApplyT(func(v *ContactProperty) ContactPropertyTypeOutput { return v.Type }).(ContactPropertyTypeOutput)
}

type ContactPropertyArrayOutput struct{ *pulumi.OutputState }

func (ContactPropertyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ContactProperty)(nil)).Elem()
}

func (o ContactPropertyArrayOutput) ToContactPropertyArrayOutput() ContactPropertyArrayOutput {
	return o
}

func (o ContactPropertyArrayOutput) ToContactPropertyArrayOutputWithContext(ctx context.Context) ContactPropertyArrayOutput {
	return o
}

func (o ContactPropertyArrayOutput) Index(i pulumi.IntInput) ContactPropertyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ContactProperty {
		return vs[0].([]*ContactProperty)[vs[1].(int)]
	}).(ContactPropertyOutput)
}

type ContactPropertyMapOutput struct{ *pulumi.OutputState }

func (ContactPropertyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ContactProperty)(nil)).Elem()
}

func (o ContactPropertyMapOutput) ToContactPropertyMapOutput() ContactPropertyMapOutput {
	return o
}

func (o ContactPropertyMapOutput) ToContactPropertyMapOutputWithContext(ctx context.Context) ContactPropertyMapOutput {
	return o
}

func (o ContactPropertyMapOutput) MapIndex(k pulumi.StringInput) ContactPropertyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ContactProperty {
		return vs[0].(map[string]*ContactProperty)[vs[1].(string)]
	}).(ContactPropertyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ContactPropertyInput)(nil)).Elem(), &ContactProperty{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContactPropertyArrayInput)(nil)).Elem(), ContactPropertyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContactPropertyMapInput)(nil)).Elem(), ContactPropertyMap{})
	pulumi.RegisterOutputType(ContactPropertyOutput{})
	pulumi.RegisterOutputType(ContactPropertyArrayOutput{})
	pulumi.RegisterOutputType(ContactPropertyMapOutput{})
}
