// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resend

import (
	"context"
	"reflect"

	"errors"
	"github.com/iwahbe/pulumi-resend/sdk/go/resend/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A domain registered with Resend for sending (and optionally receiving) email. The `records` output contains the DNS records that must be created before the domain can be verified.
type Domain struct {
	pulumi.CustomResourceState

	// Enable `sending` and/or `receiving` for this domain.
	Capabilities DomainCapabilitiesPtrOutput `pulumi:"capabilities"`
	// Track link clicks in HTML emails. Requires a verified tracking subdomain.
	ClickTracking pulumi.BoolPtrOutput `pulumi:"clickTracking"`
	CreatedAt     pulumi.StringOutput  `pulumi:"createdAt"`
	// The subdomain used for the Return-Path address. Defaults to `send`.
	CustomReturnPath pulumi.StringPtrOutput `pulumi:"customReturnPath"`
	// The domain name, e.g. `example.com`.
	Name pulumi.StringOutput `pulumi:"name"`
	// Track email open rates. Requires a verified tracking subdomain.
	OpenTracking pulumi.BoolPtrOutput `pulumi:"openTracking"`
	// The DNS records to create for this domain.
	Records DomainRecordArrayOutput `pulumi:"records"`
	// The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
	Region DomainRegionPtrOutput `pulumi:"region"`
	// The verification status of the domain.
	Status pulumi.StringOutput `pulumi:"status"`
	// Connection encryption: `opportunistic` (default) or `enforced`.
	Tls DomainTLSPtrOutput `pulumi:"tls"`
	// Custom subdomain used for open/click tracking links.
	TrackingSubdomain pulumi.StringPtrOutput `pulumi:"trackingSubdomain"`
}

// NewDomain registers a new resource with the given unique name, arguments, and options.
func NewDomain(ctx *pulumi.Context,
	name string, args *DomainArgs, opts ...pulumi.ResourceOption) (*Domain, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Domain
	err := ctx.RegisterResource("resend:index:Domain", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDomain gets an existing Domain resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDomain(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DomainState, opts ...pulumi.ResourceOption) (*Domain, error) {
	var resource Domain
	err := ctx.ReadResource("resend:index:Domain", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Domain resources.
type domainState struct {
}

type DomainState struct {
}

func (DomainState) ElementType() reflect.Type {
	return reflect.TypeOf((*domainState)(nil)).Elem()
}

type domainArgs struct {
	// Enable `sending` and/or `receiving` for this domain.
	Capabilities *DomainCapabilities `pulumi:"capabilities"`
	// Track link clicks in HTML emails. Requires a verified tracking subdomain.
	ClickTracking *bool `pulumi:"clickTracking"`
	// The subdomain used for the Return-Path address. Defaults to `send`.
	CustomReturnPath *string `pulumi:"customReturnPath"`
	// The domain name, e.g. `example.com`.
	Name string `pulumi:"name"`
	// Track email open rates. Requires a verified tracking subdomain.
	OpenTracking *bool `pulumi:"openTracking"`
	// The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
	Region *DomainRegion `pulumi:"region"`
	// Connection encryption: `opportunistic` (default) or `enforced`.
	Tls *DomainTLS `pulumi:"tls"`
	// Custom subdomain used for open/click tracking links.
	TrackingSubdomain *string `pulumi:"trackingSubdomain"`
}

// The set of arguments for constructing a Domain resource.
type DomainArgs struct {
	// Enable `sending` and/or `receiving` for this domain.
	Capabilities DomainCapabilitiesPtrInput
	// Track link clicks in HTML emails. Requires a verified tracking subdomain.
	ClickTracking pulumi.BoolPtrInput
	// The subdomain used for the Return-Path address. Defaults to `send`.
	CustomReturnPath pulumi.StringPtrInput
	// The domain name, e.g. `example.com`.
	Name pulumi.StringInput
	// Track email open rates. Requires a verified tracking subdomain.
	OpenTracking pulumi.BoolPtrInput
	// The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
	Region DomainRegionPtrInput
	// Connection encryption: `opportunistic` (default) or `enforced`.
	Tls DomainTLSPtrInput
	// Custom subdomain used for open/click tracking links.
	TrackingSubdomain pulumi.StringPtrInput
}

func (DomainArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*domainArgs)(nil)).Elem()
}

type DomainInput interface {
	pulumi.Input

	ToDomainOutput() DomainOutput
	ToDomainOutputWithContext(ctx context.Context) DomainOutput
}

func (*Domain) ElementType() reflect.Type {
	return reflect.TypeOf((**Domain)(nil)).Elem()
}

func (i *Domain) ToDomainOutput() DomainOutput {
	return i.ToDomainOutputWithContext(context.Background())
}

func (i *Domain) ToDomainOutputWithContext(ctx context.Context) DomainOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainOutput)
}

// DomainArrayInput is an input type that accepts DomainArray and DomainArrayOutput values.
// You can construct a concrete instance of `DomainArrayInput` via:
//
//	DomainArray{ DomainArgs{...} }
type DomainArrayInput interface {
	pulumi.Input

	ToDomainArrayOutput() DomainArrayOutput
	ToDomainArrayOutputWithContext(context.Context) DomainArrayOutput
}

type DomainArray []DomainInput

func (DomainArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Domain)(nil)).Elem()
}

func (i DomainArray) ToDomainArrayOutput() DomainArrayOutput {
	return i.ToDomainArrayOutputWithContext(context.Background())
}

func (i DomainArray) ToDomainArrayOutputWithContext(ctx context.Context) DomainArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainArrayOutput)
}

// DomainMapInput is an input type that accepts DomainMap and DomainMapOutput values.
// You can construct a concrete instance of `DomainMapInput` via:
//
//	DomainMap{ "key": DomainArgs{...} }
type DomainMapInput interface {
	pulumi.Input

	ToDomainMapOutput() DomainMapOutput
	ToDomainMapOutputWithContext(context.Context) DomainMapOutput
}

type DomainMap map[string]DomainInput

func (DomainMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Domain)(nil)).Elem()
}

func (i DomainMap) ToDomainMapOutput() DomainMapOutput {
	return i.ToDomainMapOutputWithContext(context.Background())
}

func (i DomainMap) ToDomainMapOutputWithContext(ctx context.Context) DomainMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainMapOutput)
}

type DomainOutput struct{ *pulumi.OutputState }

func (DomainOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Domain)(nil)).Elem()
}

func (o DomainOutput) ToDomainOutput() DomainOutput {
	return o
}

func (o DomainOutput) ToDomainOutputWithContext(ctx context.Context) DomainOutput {
	return o
}

// Enable `sending` and/or `receiving` for this domain.
func (o DomainOutput) Capabilities() DomainCapabilitiesPtrOutput {
	return o.ApplyT(func(v *Domain) DomainCapabilitiesPtrOutput { return v.Capabilities }).(DomainCapabilitiesPtrOutput)
}

// Track link clicks in HTML emails. Requires a verified tracking subdomain.
func (o DomainOutput) ClickTracking() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.BoolPtrOutput { return v.ClickTracking }).(pulumi.BoolPtrOutput)
}

func (o DomainOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The subdomain used for the Return-Path address. Defaults to `send`.
func (o DomainOutput) CustomReturnPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.CustomReturnPath }).(pulumi.StringPtrOutput)
}

// The domain name, e.g. `example.com`.
func (o DomainOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Track email open rates. Requires a verified tracking subdomain.
func (o DomainOutput) OpenTracking() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.BoolPtrOutput { return v.OpenTracking }).(pulumi.BoolPtrOutput)
}

// The DNS records to create for this domain.
func (o DomainOutput) Records() DomainRecordArrayOutput {
	return o.ApplyT(func(v *Domain) DomainRecordArrayOutput { return v.Records }).(DomainRecordArrayOutput)
}

// The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
func (o DomainOutput) Region() DomainRegionPtrOutput {
	return o.ApplyT(func(v *Domain) DomainRegionPtrOutput { return v.Region }).(DomainRegionPtrOutput)
}

// The verification status of the domain.
func (o DomainOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Connection encryption: `opportunistic` (default) or `enforced`.
func (o DomainOutput) Tls() DomainTLSPtrOutput {
	return o.ApplyT(func(v *Domain) DomainTLSPtrOutput { return v.Tls }).(DomainTLSPtrOutput)
}

// Custom subdomain used for open/click tracking links.
func (o DomainOutput) TrackingSubdomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.TrackingSubdomain }).(pulumi.StringPtrOutput)
}

type DomainArrayOutput struct{ *pulumi.OutputState }

func (DomainArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Domain)(nil)).Elem()
}

func (o DomainArrayOutput) ToDomainArrayOutput() DomainArrayOutput {
	return o
}

func (o DomainArrayOutput) ToDomainArrayOutputWithContext(ctx context.Context) DomainArrayOutput {
	return o
}

func (o DomainArrayOutput) Index(i pulumi.IntInput) DomainOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Domain {
		return vs[0].([]*Domain)[vs[1].(int)]
	}).(DomainOutput)
}

type DomainMapOutput struct{ *pulumi.OutputState }

func (DomainMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Domain)(nil)).Elem()
}

func (o DomainMapOutput) ToDomainMapOutput() DomainMapOutput {
	return o
}

func (o DomainMapOutput) ToDomainMapOutputWithContext(ctx context.Context) DomainMapOutput {
	return o
}

func (o DomainMapOutput) MapIndex(k pulumi.StringInput) DomainOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Domain {
		return vs[0].(map[string]*Domain)[vs[1].(string)]
	}).(DomainOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainInput)(nil)).Elem(), &Domain{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainArrayInput)(nil)).Elem(), DomainArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainMapInput)(nil)).Elem(), DomainMap{})
	pulumi.RegisterOutputType(DomainOutput{})
	pulumi.RegisterOutputType(DomainArrayOutput{})
	pulumi.RegisterOutputType(DomainMapOutput{})
}
