// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resend

import (
	"context"
	"reflect"

	"errors"
	"github.com/iwahbe/pulumi-resend/sdk/go/resend/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Triggers verification of a Resend domain and waits until the domain's DNS records have been verified. Create this resource after the domain's DNS records (from the `Domain` resource's `records` output) have been published.
type DomainVerification struct {
	pulumi.CustomResourceState

	// The ID of the domain to verify.
	DomainId pulumi.StringOutput `pulumi:"domainId"`
	// The verification status of the domain.
	Status pulumi.StringOutput `pulumi:"status"`
	// How long to wait for verification before failing. Defaults to 900 seconds.
	TimeoutSeconds pulumi.IntPtrOutput `pulumi:"timeoutSeconds"`
}

// NewDomainVerification registers a new resource with the given unique name, arguments, and options.
func NewDomainVerification(ctx *pulumi.Context,
	name string, args *DomainVerificationArgs, opts ...pulumi.ResourceOption) (*DomainVerification, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DomainId == nil {
		return nil, errors.New("invalid value for required argument 'DomainId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DomainVerification
	err := ctx.RegisterResource("resend:index:DomainVerification", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDomainVerification gets an existing DomainVerification resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDomainVerification(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DomainVerificationState, opts ...pulumi.ResourceOption) (*DomainVerification, error) {
	var resource DomainVerification
	err := ctx.ReadResource("resend:index:DomainVerification", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DomainVerification resources.
type domainVerificationState struct {
}

type DomainVerificationState struct {
}

func (DomainVerificationState) ElementType() reflect.Type {
	return reflect.TypeOf((*domainVerificationState)(nil)).Elem()
}

type domainVerificationArgs struct {
	// The ID of the domain to verify.
	DomainId string `pulumi:"domainId"`
	// How long to wait for verification before failing. Defaults to 900 seconds.
	TimeoutSeconds *int `pulumi:"timeoutSeconds"`
}

// The set of arguments for constructing a DomainVerification resource.
type DomainVerificationArgs struct {
	// The ID of the domain to verify.
	DomainId pulumi.StringInput
	// How long to wait for verification before failing. Defaults to 900 seconds.
	TimeoutSeconds pulumi.IntPtrInput
}

func (DomainVerificationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*domainVerificationArgs)(nil)).Elem()
}

type DomainVerificationInput interface {
	pulumi.Input

	ToDomainVerificationOutput() DomainVerificationOutput
	ToDomainVerificationOutputWithContext(ctx context.Context) DomainVerificationOutput
}

func (*DomainVerification) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainVerification)(nil)).Elem()
}

func (i *DomainVerification) ToDomainVerificationOutput() DomainVerificationOutput {
	return i.ToDomainVerificationOutputWithContext(context.Background())
}

func (i *DomainVerification) ToDomainVerificationOutputWithContext(ctx context.Context) DomainVerificationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainVerificationOutput)
}

// DomainVerificationArrayInput is an input type that accepts DomainVerificationArray and DomainVerificationArrayOutput values.
// You can construct a concrete instance of `DomainVerificationArrayInput` via:
//
//	DomainVerificationArray{ DomainVerificationArgs{...} }
type DomainVerificationArrayInput interface {
	pulumi.Input

	ToDomainVerificationArrayOutput() DomainVerificationArrayOutput
	ToDomainVerificationArrayOutputWithContext(context.Context) DomainVerificationArrayOutput
}

type DomainVerificationArray []DomainVerificationInput

func (DomainVerificationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DomainVerification)(nil)).Elem()
}

func (i DomainVerificationArray) ToDomainVerificationArrayOutput() DomainVerificationArrayOutput {
	return i.ToDomainVerificationArrayOutputWithContext(context.Background())
}

func (i DomainVerificationArray) ToDomainVerificationArrayOutputWithContext(ctx context.Context) DomainVerificationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainVerificationArrayOutput)
}

// DomainVerificationMapInput is an input type that accepts DomainVerificationMap and DomainVerificationMapOutput values.
// You can construct a concrete instance of `DomainVerificationMapInput` via:
//
//	DomainVerificationMap{ "key": DomainVerificationArgs{...} }
type DomainVerificationMapInput interface {
	pulumi.Input

	ToDomainVerificationMapOutput() DomainVerificationMapOutput
	ToDomainVerificationMapOutputWithContext(context.Context) DomainVerificationMapOutput
}

type DomainVerificationMap map[string]DomainVerificationInput

func (DomainVerificationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DomainVerification)(nil)).Elem()
}

func (i DomainVerificationMap) ToDomainVerificationMapOutput() DomainVerificationMapOutput {
	return i.ToDomainVerificationMapOutputWithContext(context.Background())
}

func (i DomainVerificationMap) ToDomainVerificationMapOutputWithContext(ctx context.Context) DomainVerificationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainVerificationMapOutput)
}

type DomainVerificationOutput struct{ *pulumi.OutputState }

func (DomainVerificationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainVerification)(nil)).Elem()
}

func (o DomainVerificationOutput) ToDomainVerificationOutput() DomainVerificationOutput {
	return o
}

func (o DomainVerificationOutput) ToDomainVerificationOutputWithContext(ctx context.Context) DomainVerificationOutput {
	return o
}

// The ID of the domain to verify.
func (o DomainVerificationOutput) DomainId() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainVerification) pulumi.StringOutput { return v.DomainId }).(pulumi.StringOutput)
}

// The verification status of the domain.
func (o DomainVerificationOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainVerification) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// How long to wait for verification before failing. Defaults to 900 seconds.
func (o DomainVerificationOutput) TimeoutSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DomainVerification) pulumi.IntPtrOutput { return v.TimeoutSeconds }).(pulumi.IntPtrOutput)
}

type DomainVerificationArrayOutput struct{ *pulumi.OutputState }

func (DomainVerificationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DomainVerification)(nil)).Elem()
}

func (o DomainVerificationArrayOutput) ToDomainVerificationArrayOutput() DomainVerificationArrayOutput {
	return o
}

func (o DomainVerificationArrayOutput) ToDomainVerificationArrayOutputWithContext(ctx context.Context) DomainVerificationArrayOutput {
	return o
}

func (o DomainVerificationArrayOutput) Index(i pulumi.IntInput) DomainVerificationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DomainVerification {
		return vs[0].([]*DomainVerification)[vs[1].(int)]
	}).(DomainVerificationOutput)
}

type DomainVerificationMapOutput struct{ *pulumi.OutputState }

func (DomainVerificationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DomainVerification)(nil)).Elem()
}

func (o DomainVerificationMapOutput) ToDomainVerificationMapOutput() DomainVerificationMapOutput {
	return o
}

func (o DomainVerificationMapOutput) ToDomainVerificationMapOutputWithContext(ctx context.Context) DomainVerificationMapOutput {
	return o
}

func (o DomainVerificationMapOutput) MapIndex(k pulumi.StringInput) DomainVerificationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DomainVerification {
		return vs[0].(map[string]*DomainVerification)[vs[1].(string)]
	}).(DomainVerificationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainVerificationInput)(nil)).Elem(), &DomainVerification{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainVerificationArrayInput)(nil)).Elem(), DomainVerificationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainVerificationMapInput)(nil)).Elem(), DomainVerificationMap{})
	pulumi.RegisterOutputType(DomainVerificationOutput{})
	pulumi.RegisterOutputType(DomainVerificationArrayOutput{})
	pulumi.RegisterOutputType(DomainVerificationMapOutput{})
}
