// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resend

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ApiKeyPermission string

const (
	// Full access to the Resend API.
	ApiKeyPermission_Full_access = ApiKeyPermission("full_access")
	// Permission to send emails.
	ApiKeyPermission_Sending_access = ApiKeyPermission("sending_access")
)

func (ApiKeyPermission) ElementType() reflect.Type {
	return reflect.TypeOf((*ApiKeyPermission)(nil)).Elem()
}

func (e ApiKeyPermission) ToApiKeyPermissionOutput() ApiKeyPermissionOutput {
	return pulumi.ToOutput(e).(ApiKeyPermissionOutput)
}

func (e ApiKeyPermission) ToApiKeyPermissionOutputWithContext(ctx context.Context) ApiKeyPermissionOutput {
	return pulumi.ToOutputWithContext(ctx, e).(ApiKeyPermissionOutput)
}

func (e ApiKeyPermission) ToApiKeyPermissionPtrOutput() ApiKeyPermissionPtrOutput {
	return e.ToApiKeyPermissionPtrOutputWithContext(context.Background())
}

func (e ApiKeyPermission) ToApiKeyPermissionPtrOutputWithContext(ctx context.Context) ApiKeyPermissionPtrOutput {
	return ApiKeyPermission(e).ToApiKeyPermissionOutputWithContext(ctx).ToApiKeyPermissionPtrOutputWithContext(ctx)
}

func (e ApiKeyPermission) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e ApiKeyPermission) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e ApiKeyPermission) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e ApiKeyPermission) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type ApiKeyPermissionOutput struct{ *pulumi.OutputState }

func (ApiKeyPermissionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ApiKeyPermission)(nil)).Elem()
}

func (o ApiKeyPermissionOutput) ToApiKeyPermissionOutput() ApiKeyPermissionOutput {
	return o
}

func (o ApiKeyPermissionOutput) ToApiKeyPermissionOutputWithContext(ctx context.Context) ApiKeyPermissionOutput {
	return o
}

func (o ApiKeyPermissionOutput) ToApiKeyPermissionPtrOutput() ApiKeyPermissionPtrOutput {
	return o.ToApiKeyPermissionPtrOutputWithContext(context.Background())
}

func (o ApiKeyPermissionOutput) ToApiKeyPermissionPtrOutputWithContext(ctx context.Context) ApiKeyPermissionPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ApiKeyPermission) *ApiKeyPermission {
		return &v
	}).(ApiKeyPermissionPtrOutput)
}

func (o ApiKeyPermissionOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ApiKeyPermissionOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ApiKeyPermission) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o ApiKeyPermissionOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ApiKeyPermissionOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ApiKeyPermission) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type ApiKeyPermissionPtrOutput struct{ *pulumi.OutputState }

func (ApiKeyPermissionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ApiKeyPermission)(nil)).Elem()
}

func (o ApiKeyPermissionPtrOutput) ToApiKeyPermissionPtrOutput() ApiKeyPermissionPtrOutput {
	return o
}

func (o ApiKeyPermissionPtrOutput) ToApiKeyPermissionPtrOutputWithContext(ctx context.Context) ApiKeyPermissionPtrOutput {
	return o
}

func (o ApiKeyPermissionPtrOutput) Elem() ApiKeyPermissionOutput {
	return o.ApplyT(func(v *ApiKeyPermission) ApiKeyPermission {
		if v != nil {
			return *v
		}
		var ret ApiKeyPermission
		return ret
	}).(ApiKeyPermissionOutput)
}

func (o ApiKeyPermissionPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ApiKeyPermissionPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *ApiKeyPermission) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// ApiKeyPermissionInput is an input type that accepts values of the ApiKeyPermission enum
// A concrete instance of `ApiKeyPermissionInput` can be one of the following:
//
//	ApiKeyPermission_Full_access
//	ApiKeyPermission_Sending_access
type ApiKeyPermissionInput interface {
	pulumi.Input

	ToApiKeyPermissionOutput() ApiKeyPermissionOutput
	ToApiKeyPermissionOutputWithContext(context.Context) ApiKeyPermissionOutput
}

var apiKeyPermissionPtrType = reflect.TypeOf((**ApiKeyPermission)(nil)).Elem()

type ApiKeyPermissionPtrInput interface {
	pulumi.Input

	ToApiKeyPermissionPtrOutput() ApiKeyPermissionPtrOutput
	ToApiKeyPermissionPtrOutputWithContext(context.Context) ApiKeyPermissionPtrOutput
}

type apiKeyPermissionPtr string

func ApiKeyPermissionPtr(v string) ApiKeyPermissionPtrInput {
	return (*apiKeyPermissionPtr)(&v)
}

func (*apiKeyPermissionPtr) ElementType() reflect.Type {
	return apiKeyPermissionPtrType
}

func (in *apiKeyPermissionPtr) ToApiKeyPermissionPtrOutput() ApiKeyPermissionPtrOutput {
	return pulumi.ToOutput(in).(ApiKeyPermissionPtrOutput)
}

func (in *apiKeyPermissionPtr) ToApiKeyPermissionPtrOutputWithContext(ctx context.Context) ApiKeyPermissionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(ApiKeyPermissionPtrOutput)
}

type DomainCapabilityStatus string

const (
	DomainCapabilityStatusEnabled  = DomainCapabilityStatus("enabled")
	DomainCapabilityStatusDisabled = DomainCapabilityStatus("disabled")
)

func (DomainCapabilityStatus) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainCapabilityStatus)(nil)).Elem()
}

func (e DomainCapabilityStatus) ToDomainCapabilityStatusOutput() DomainCapabilityStatusOutput {
	return pulumi.ToOutput(e).(DomainCapabilityStatusOutput)
}

func (e DomainCapabilityStatus) ToDomainCapabilityStatusOutputWithContext(ctx context.Context) DomainCapabilityStatusOutput {
	return pulumi.ToOutputWithContext(ctx, e).(DomainCapabilityStatusOutput)
}

func (e DomainCapabilityStatus) ToDomainCapabilityStatusPtrOutput() DomainCapabilityStatusPtrOutput {
	return e.ToDomainCapabilityStatusPtrOutputWithContext(context.Background())
}

func (e DomainCapabilityStatus) ToDomainCapabilityStatusPtrOutputWithContext(ctx context.Context) DomainCapabilityStatusPtrOutput {
	return DomainCapabilityStatus(e).ToDomainCapabilityStatusOutputWithContext(ctx).ToDomainCapabilityStatusPtrOutputWithContext(ctx)
}

func (e DomainCapabilityStatus) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e DomainCapabilityStatus) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e DomainCapabilityStatus) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e DomainCapabilityStatus) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type DomainCapabilityStatusOutput struct{ *pulumi.OutputState }

func (DomainCapabilityStatusOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainCapabilityStatus)(nil)).Elem()
}

func (o DomainCapabilityStatusOutput) ToDomainCapabilityStatusOutput() DomainCapabilityStatusOutput {
	return o
}

func (o DomainCapabilityStatusOutput) ToDomainCapabilityStatusOutputWithContext(ctx context.Context) DomainCapabilityStatusOutput {
	return o
}

func (o DomainCapabilityStatusOutput) ToDomainCapabilityStatusPtrOutput() DomainCapabilityStatusPtrOutput {
	return o.ToDomainCapabilityStatusPtrOutputWithContext(context.Background())
}

func (o DomainCapabilityStatusOutput) ToDomainCapabilityStatusPtrOutputWithContext(ctx context.Context) DomainCapabilityStatusPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DomainCapabilityStatus) *DomainCapabilityStatus {
		return &v
	}).(DomainCapabilityStatusPtrOutput)
}

func (o DomainCapabilityStatusOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o DomainCapabilityStatusOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e DomainCapabilityStatus) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o DomainCapabilityStatusOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o DomainCapabilityStatusOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e DomainCapabilityStatus) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type DomainCapabilityStatusPtrOutput struct{ *pulumi.OutputState }

func (DomainCapabilityStatusPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainCapabilityStatus)(nil)).Elem()
}

func (o DomainCapabilityStatusPtrOutput) ToDomainCapabilityStatusPtrOutput() DomainCapabilityStatusPtrOutput {
	return o
}

func (o DomainCapabilityStatusPtrOutput) ToDomainCapabilityStatusPtrOutputWithContext(ctx context.Context) DomainCapabilityStatusPtrOutput {
	return o
}

func (o DomainCapabilityStatusPtrOutput) Elem() DomainCapabilityStatusOutput {
	return o.ApplyT(func(v *DomainCapabilityStatus) DomainCapabilityStatus {
		if v != nil {
			return *v
		}
		var ret DomainCapabilityStatus
		return ret
	}).(DomainCapabilityStatusOutput)
}

func (o DomainCapabilityStatusPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o DomainCapabilityStatusPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *DomainCapabilityStatus) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// DomainCapabilityStatusInput is an input type that accepts values of the DomainCapabilityStatus enum
// A concrete instance of `DomainCapabilityStatusInput` can be one of the following:
//
//	DomainCapabilityStatusEnabled
//	DomainCapabilityStatusDisabled
type DomainCapabilityStatusInput interface {
	pulumi.Input

	ToDomainCapabilityStatusOutput() DomainCapabilityStatusOutput
	ToDomainCapabilityStatusOutputWithContext(context.Context) DomainCapabilityStatusOutput
}

var domainCapabilityStatusPtrType = reflect.TypeOf((**DomainCapabilityStatus)(nil)).Elem()

type DomainCapabilityStatusPtrInput interface {
	pulumi.Input

	ToDomainCapabilityStatusPtrOutput() DomainCapabilityStatusPtrOutput
	ToDomainCapabilityStatusPtrOutputWithContext(context.Context) DomainCapabilityStatusPtrOutput
}

type domainCapabilityStatusPtr string

func DomainCapabilityStatusPtr(v string) DomainCapabilityStatusPtrInput {
	return (*domainCapabilityStatusPtr)(&v)
}

func (*domainCapabilityStatusPtr) ElementType() reflect.Type {
	return domainCapabilityStatusPtrType
}

func (in *domainCapabilityStatusPtr) ToDomainCapabilityStatusPtrOutput() DomainCapabilityStatusPtrOutput {
	return pulumi.ToOutput(in).(DomainCapabilityStatusPtrOutput)
}

func (in *domainCapabilityStatusPtr) ToDomainCapabilityStatusPtrOutputWithContext(ctx context.Context) DomainCapabilityStatusPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(DomainCapabilityStatusPtrOutput)
}

type DomainRegion string

const (
	DomainRegion_Us_East_1      = DomainRegion("us-east-1")
	DomainRegion_Eu_West_1      = DomainRegion("eu-west-1")
	DomainRegion_Sa_East_1      = DomainRegion("sa-east-1")
	DomainRegion_Ap_Northeast_1 = DomainRegion("ap-northeast-1")
)

func (DomainRegion) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainRegion)(nil)).Elem()
}

func (e DomainRegion) ToDomainRegionOutput() DomainRegionOutput {
	return pulumi.ToOutput(e).(DomainRegionOutput)
}

func (e DomainRegion) ToDomainRegionOutputWithContext(ctx context.Context) DomainRegionOutput {
	return pulumi.ToOutputWithContext(ctx, e).(DomainRegionOutput)
}

func (e DomainRegion) ToDomainRegionPtrOutput() DomainRegionPtrOutput {
	return e.ToDomainRegionPtrOutputWithContext(context.Background())
}

func (e DomainRegion) ToDomainRegionPtrOutputWithContext(ctx context.Context) DomainRegionPtrOutput {
	return DomainRegion(e).ToDomainRegionOutputWithContext(ctx).ToDomainRegionPtrOutputWithContext(ctx)
}

func (e DomainRegion) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e DomainRegion) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e DomainRegion) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e DomainRegion) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type DomainRegionOutput struct{ *pulumi.OutputState }

func (DomainRegionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainRegion)(nil)).Elem()
}

func (o DomainRegionOutput) ToDomainRegionOutput() DomainRegionOutput {
	return o
}

func (o DomainRegionOutput) ToDomainRegionOutputWithContext(ctx context.Context) DomainRegionOutput {
	return o
}

func (o DomainRegionOutput) ToDomainRegionPtrOutput() DomainRegionPtrOutput {
	return o.ToDomainRegionPtrOutputWithContext(context.Background())
}

func (o DomainRegionOutput) ToDomainRegionPtrOutputWithContext(ctx context.Context) DomainRegionPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DomainRegion) *DomainRegion {
		return &v
	}).(DomainRegionPtrOutput)
}

func (o DomainRegionOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o DomainRegionOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e DomainRegion) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o DomainRegionOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o DomainRegionOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e DomainRegion) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type DomainRegionPtrOutput struct{ *pulumi.OutputState }

func (DomainRegionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainRegion)(nil)).Elem()
}

func (o DomainRegionPtrOutput) ToDomainRegionPtrOutput() DomainRegionPtrOutput {
	return o
}

func (o DomainRegionPtrOutput) ToDomainRegionPtrOutputWithContext(ctx context.Context) DomainRegionPtrOutput {
	return o
}

func (o DomainRegionPtrOutput) Elem() DomainRegionOutput {
	return o.ApplyT(func(v *DomainRegion) DomainRegion {
		if v != nil {
			return *v
		}
		var ret DomainRegion
		return ret
	}).(DomainRegionOutput)
}

func (o DomainRegionPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o DomainRegionPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *DomainRegion) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// DomainRegionInput is an input type that accepts values of the DomainRegion enum
// A concrete instance of `DomainRegionInput` can be one of the following:
//
//	DomainRegion_Us_East_1
//	DomainRegion_Eu_West_1
//	DomainRegion_Sa_East_1
//	DomainRegion_Ap_Northeast_1
type DomainRegionInput interface {
	pulumi.Input

	ToDomainRegionOutput() DomainRegionOutput
	ToDomainRegionOutputWithContext(context.Context) DomainRegionOutput
}

var domainRegionPtrType = reflect.TypeOf((**DomainRegion)(nil)).Elem()

type DomainRegionPtrInput interface {
	pulumi.Input

	ToDomainRegionPtrOutput() DomainRegionPtrOutput
	ToDomainRegionPtrOutputWithContext(context.Context) DomainRegionPtrOutput
}

type domainRegionPtr string

func DomainRegionPtr(v string) DomainRegionPtrInput {
	return (*domainRegionPtr)(&v)
}

func (*domainRegionPtr) ElementType() reflect.Type {
	return domainRegionPtrType
}

func (in *domainRegionPtr) ToDomainRegionPtrOutput() DomainRegionPtrOutput {
	return pulumi.ToOutput(in).(DomainRegionPtrOutput)
}

func (in *domainRegionPtr) ToDomainRegionPtrOutputWithContext(ctx context.Context) DomainRegionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(DomainRegionPtrOutput)
}

type DomainTLS string

const (
	DomainTLSEnforced      = DomainTLS("enforced")
	DomainTLSOpportunistic = DomainTLS("opportunistic")
)

func (DomainTLS) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainTLS)(nil)).Elem()
}

func (e DomainTLS) ToDomainTLSOutput() DomainTLSOutput {
	return pulumi.ToOutput(e).(DomainTLSOutput)
}

func (e DomainTLS) ToDomainTLSOutputWithContext(ctx context.Context) DomainTLSOutput {
	return pulumi.ToOutputWithContext(ctx, e).(DomainTLSOutput)
}

func (e DomainTLS) ToDomainTLSPtrOutput() DomainTLSPtrOutput {
	return e.ToDomainTLSPtrOutputWithContext(context.Background())
}

func (e DomainTLS) ToDomainTLSPtrOutputWithContext(ctx context.Context) DomainTLSPtrOutput {
	return DomainTLS(e).ToDomainTLSOutputWithContext(ctx).ToDomainTLSPtrOutputWithContext(ctx)
}

func (e DomainTLS) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e DomainTLS) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e DomainTLS) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e DomainTLS) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type DomainTLSOutput struct{ *pulumi.OutputState }

func (DomainTLSOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainTLS)(nil)).Elem()
}

func (o DomainTLSOutput) ToDomainTLSOutput() DomainTLSOutput {
	return o
}

func (o DomainTLSOutput) ToDomainTLSOutputWithContext(ctx context.Context) DomainTLSOutput {
	return o
}

func (o DomainTLSOutput) ToDomainTLSPtrOutput() DomainTLSPtrOutput {
	return o.ToDomainTLSPtrOutputWithContext(context.Background())
}

func (o DomainTLSOutput) ToDomainTLSPtrOutputWithContext(ctx context.Context) DomainTLSPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DomainTLS) *DomainTLS {
		return &v
	}).(DomainTLSPtrOutput)
}

func (o DomainTLSOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o DomainTLSOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e DomainTLS) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o DomainTLSOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o DomainTLSOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e DomainTLS) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type DomainTLSPtrOutput struct{ *pulumi.OutputState }

func (DomainTLSPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainTLS)(nil)).Elem()
}

func (o DomainTLSPtrOutput) ToDomainTLSPtrOutput() DomainTLSPtrOutput {
	return o
}

func (o DomainTLSPtrOutput) ToDomainTLSPtrOutputWithContext(ctx context.Context) DomainTLSPtrOutput {
	return o
}

func (o DomainTLSPtrOutput) Elem() DomainTLSOutput {
	return o.ApplyT(func(v *DomainTLS) DomainTLS {
		if v != nil {
			return *v
		}
		var ret DomainTLS
		return ret
	}).(DomainTLSOutput)
}

func (o DomainTLSPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o DomainTLSPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *DomainTLS) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// DomainTLSInput is an input type that accepts values of the DomainTLS enum
// A concrete instance of `DomainTLSInput` can be one of the following:
//
//	DomainTLSEnforced
//	DomainTLSOpportunistic
type DomainTLSInput interface {
	pulumi.Input

	ToDomainTLSOutput() DomainTLSOutput
	ToDomainTLSOutputWithContext(context.Context) DomainTLSOutput
}

var domainTLSPtrType = reflect.TypeOf((**DomainTLS)(nil)).Elem()

type DomainTLSPtrInput interface {
	pulumi.Input

	ToDomainTLSPtrOutput() DomainTLSPtrOutput
	ToDomainTLSPtrOutputWithContext(context.Context) DomainTLSPtrOutput
}

type domainTLSPtr string

func DomainTLSPtr(v string) DomainTLSPtrInput {
	return (*domainTLSPtr)(&v)
}

func (*domainTLSPtr) ElementType() reflect.Type {
	return domainTLSPtrType
}

func (in *domainTLSPtr) ToDomainTLSPtrOutput() DomainTLSPtrOutput {
	return pulumi.ToOutput(in).(DomainTLSPtrOutput)
}

func (in *domainTLSPtr) ToDomainTLSPtrOutputWithContext(ctx context.Context) DomainTLSPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(DomainTLSPtrOutput)
}

type WebhookEvent string

const (
	WebhookEvent_Email_sent             = WebhookEvent("email.sent")
	WebhookEvent_Email_delivered        = WebhookEvent("email.delivered")
	WebhookEvent_Email_delivery_delayed = WebhookEvent("email.delivery_delayed")
	WebhookEvent_Email_complained       = WebhookEvent("email.complained")
	WebhookEvent_Email_bounced          = WebhookEvent("email.bounced")
	WebhookEvent_Email_opened           = WebhookEvent("email.opened")
	WebhookEvent_Email_clicked          = WebhookEvent("email.clicked")
	WebhookEvent_Email_received         = WebhookEvent("email.received")
	WebhookEvent_Email_failed           = WebhookEvent("email.failed")
	WebhookEvent_Email_scheduled        = WebhookEvent("email.scheduled")
	WebhookEvent_Email_suppressed       = WebhookEvent("email.suppressed")
	WebhookEvent_Contact_created        = WebhookEvent("contact.created")
	WebhookEvent_Contact_updated        = WebhookEvent("contact.updated")
	WebhookEvent_Contact_deleted        = WebhookEvent("contact.deleted")
	WebhookEvent_Domain_created         = WebhookEvent("domain.created")
	WebhookEvent_Domain_updated         = WebhookEvent("domain.updated")
	WebhookEvent_Domain_deleted         = WebhookEvent("domain.deleted")
)

func (WebhookEvent) ElementType() reflect.Type {
	return reflect.TypeOf((*WebhookEvent)(nil)).Elem()
}

func (e WebhookEvent) ToWebhookEventOutput() WebhookEventOutput {
	return pulumi.ToOutput(e).(WebhookEventOutput)
}

func (e WebhookEvent) ToWebhookEventOutputWithContext(ctx context.Context) WebhookEventOutput {
	return pulumi.ToOutputWithContext(ctx, e).(WebhookEventOutput)
}

func (e WebhookEvent) ToWebhookEventPtrOutput() WebhookEventPtrOutput {
	return e.ToWebhookEventPtrOutputWithContext(context.Background())
}

func (e WebhookEvent) ToWebhookEventPtrOutputWithContext(ctx context.Context) WebhookEventPtrOutput {
	return WebhookEvent(e).ToWebhookEventOutputWithContext(ctx).ToWebhookEventPtrOutputWithContext(ctx)
}

func (e WebhookEvent) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e WebhookEvent) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e WebhookEvent) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e WebhookEvent) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type WebhookEventOutput struct{ *pulumi.OutputState }

func (WebhookEventOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WebhookEvent)(nil)).Elem()
}

func (o WebhookEventOutput) ToWebhookEventOutput() WebhookEventOutput {
	return o
}

func (o WebhookEventOutput) ToWebhookEventOutputWithContext(ctx context.Context) WebhookEventOutput {
	return o
}

func (o WebhookEventOutput) ToWebhookEventPtrOutput() WebhookEventPtrOutput {
	return o.ToWebhookEventPtrOutputWithContext(context.Background())
}

func (o WebhookEventOutput) ToWebhookEventPtrOutputWithContext(ctx context.Context) WebhookEventPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v WebhookEvent) *WebhookEvent {
		return &v
	}).(WebhookEventPtrOutput)
}

func (o WebhookEventOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o WebhookEventOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e WebhookEvent) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o WebhookEventOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o WebhookEventOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e WebhookEvent) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type WebhookEventPtrOutput struct{ *pulumi.OutputState }

func (WebhookEventPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WebhookEvent)(nil)).Elem()
}

func (o WebhookEventPtrOutput) ToWebhookEventPtrOutput() WebhookEventPtrOutput {
	return o
}

func (o WebhookEventPtrOutput) ToWebhookEventPtrOutputWithContext(ctx context.Context) WebhookEventPtrOutput {
	return o
}

func (o WebhookEventPtrOutput) Elem() WebhookEventOutput {
	return o.ApplyT(func(v *WebhookEvent) WebhookEvent {
		if v != nil {
			return *v
		}
		var ret WebhookEvent
		return ret
	}).(WebhookEventOutput)
}

func (o WebhookEventPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o WebhookEventPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *WebhookEvent) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// WebhookEventInput is an input type that accepts values of the WebhookEvent enum
// A concrete instance of `WebhookEventInput` can be one of the following:
//
//	WebhookEvent_Email_sent
//	WebhookEvent_Email_delivered
//	WebhookEvent_Email_delivery_delayed
//	WebhookEvent_Email_complained
//	WebhookEvent_Email_bounced
//	WebhookEvent_Email_opened
//	WebhookEvent_Email_clicked
//	WebhookEvent_Email_received
//	WebhookEvent_Email_failed
//	WebhookEvent_Email_scheduled
//	WebhookEvent_Email_suppressed
//	WebhookEvent_Contact_created
//	WebhookEvent_Contact_updated
//	WebhookEvent_Contact_deleted
//	WebhookEvent_Domain_created
//	WebhookEvent_Domain_updated
//	WebhookEvent_Domain_deleted
type WebhookEventInput interface {
	pulumi.Input

	ToWebhookEventOutput() WebhookEventOutput
	ToWebhookEventOutputWithContext(context.Context) WebhookEventOutput
}

var webhookEventPtrType = reflect.TypeOf((**WebhookEvent)(nil)).Elem()

type WebhookEventPtrInput interface {
	pulumi.Input

	ToWebhookEventPtrOutput() WebhookEventPtrOutput
	ToWebhookEventPtrOutputWithContext(context.Context) WebhookEventPtrOutput
}

type webhookEventPtr string

func WebhookEventPtr(v string) WebhookEventPtrInput {
	return (*webhookEventPtr)(&v)
}

func (*webhookEventPtr) ElementType() reflect.Type {
	return webhookEventPtrType
}

func (in *webhookEventPtr) ToWebhookEventPtrOutput() WebhookEventPtrOutput {
	return pulumi.ToOutput(in).(WebhookEventPtrOutput)
}

func (in *webhookEventPtr) ToWebhookEventPtrOutputWithContext(ctx context.Context) WebhookEventPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(WebhookEventPtrOutput)
}

// WebhookEventArrayInput is an input type that accepts WebhookEventArray and WebhookEventArrayOutput values.
// You can construct a concrete instance of `WebhookEventArrayInput` via:
//
//	WebhookEventArray{ WebhookEventArgs{...} }
type WebhookEventArrayInput interface {
	pulumi.Input

	ToWebhookEventArrayOutput() WebhookEventArrayOutput
	ToWebhookEventArrayOutputWithContext(context.Context) WebhookEventArrayOutput
}

type WebhookEventArray []WebhookEvent

func (WebhookEventArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]WebhookEvent)(nil)).Elem()
}

func (i WebhookEventArray) ToWebhookEventArrayOutput() WebhookEventArrayOutput {
	return i.ToWebhookEventArrayOutputWithContext(context.Background())
}

func (i WebhookEventArray) ToWebhookEventArrayOutputWithContext(ctx context.Context) WebhookEventArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebhookEventArrayOutput)
}

type WebhookEventArrayOutput struct{ *pulumi.OutputState }

func (WebhookEventArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]WebhookEvent)(nil)).Elem()
}

func (o WebhookEventArrayOutput) ToWebhookEventArrayOutput() WebhookEventArrayOutput {
	return o
}

func (o WebhookEventArrayOutput) ToWebhookEventArrayOutputWithContext(ctx context.Context) WebhookEventArrayOutput {
	return o
}

func (o WebhookEventArrayOutput) Index(i pulumi.IntInput) WebhookEventOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) WebhookEvent {
		return vs[0].([]WebhookEvent)[vs[1].(int)]
	}).(WebhookEventOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ApiKeyPermissionInput)(nil)).Elem(), ApiKeyPermission("full_access"))
	pulumi.RegisterInputType(reflect.TypeOf((*ApiKeyPermissionPtrInput)(nil)).Elem(), ApiKeyPermission("full_access"))
	pulumi.RegisterInputType(reflect.TypeOf((*DomainCapabilityStatusInput)(nil)).Elem(), DomainCapabilityStatus("enabled"))
	pulumi.RegisterInputType(reflect.TypeOf((*DomainCapabilityStatusPtrInput)(nil)).Elem(), DomainCapabilityStatus("enabled"))
	pulumi.RegisterInputType(reflect.TypeOf((*DomainRegionInput)(nil)).Elem(), DomainRegion("us-east-1"))
	pulumi.RegisterInputType(reflect.TypeOf((*DomainRegionPtrInput)(nil)).Elem(), DomainRegion("us-east-1"))
	pulumi.RegisterInputType(reflect.TypeOf((*DomainTLSInput)(nil)).Elem(), DomainTLS("enforced"))
	pulumi.RegisterInputType(reflect.TypeOf((*DomainTLSPtrInput)(nil)).Elem(), DomainTLS("enforced"))
	pulumi.RegisterInputType(reflect.TypeOf((*WebhookEventInput)(nil)).Elem(), WebhookEvent("email.sent"))
	pulumi.RegisterInputType(reflect.TypeOf((*WebhookEventPtrInput)(nil)).Elem(), WebhookEvent("email.sent"))
	pulumi.RegisterInputType(reflect.TypeOf((*WebhookEventArrayInput)(nil)).Elem(), WebhookEventArray{})
	pulumi.RegisterOutputType(ApiKeyPermissionOutput{})
	pulumi.RegisterOutputType(ApiKeyPermissionPtrOutput{})
	pulumi.RegisterOutputType(DomainCapabilityStatusOutput{})
	pulumi.RegisterOutputType(DomainCapabilityStatusPtrOutput{})
	pulumi.RegisterOutputType(DomainRegionOutput{})
	pulumi.RegisterOutputType(DomainRegionPtrOutput{})
	pulumi.RegisterOutputType(DomainTLSOutput{})
	pulumi.RegisterOutputType(DomainTLSPtrOutput{})
	pulumi.RegisterOutputType(WebhookEventOutput{})
	pulumi.RegisterOutputType(WebhookEventPtrOutput{})
	pulumi.RegisterOutputType(WebhookEventArrayOutput{})
}
