// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resend

import (
	"context"
	"reflect"

	"github.com/iwahbe/pulumi-resend/sdk/go/resend/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type DomainCapabilities struct {
	Receiving *DomainCapabilityStatus `pulumi:"receiving"`
	Sending   *DomainCapabilityStatus `pulumi:"sending"`
}

// DomainCapabilitiesInput is an input type that accepts DomainCapabilitiesArgs and DomainCapabilitiesOutput values.
// You can construct a concrete instance of `DomainCapabilitiesInput` via:
//
//	DomainCapabilitiesArgs{...}
type DomainCapabilitiesInput interface {
	pulumi.Input

	ToDomainCapabilitiesOutput() DomainCapabilitiesOutput
	ToDomainCapabilitiesOutputWithContext(context.Context) DomainCapabilitiesOutput
}

type DomainCapabilitiesArgs struct {
	Receiving DomainCapabilityStatusPtrInput `pulumi:"receiving"`
	Sending   DomainCapabilityStatusPtrInput `pulumi:"sending"`
}

func (DomainCapabilitiesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainCapabilities)(nil)).Elem()
}

func (i DomainCapabilitiesArgs) ToDomainCapabilitiesOutput() DomainCapabilitiesOutput {
	return i.ToDomainCapabilitiesOutputWithContext(context.Background())
}

func (i DomainCapabilitiesArgs) ToDomainCapabilitiesOutputWithContext(ctx context.Context) DomainCapabilitiesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainCapabilitiesOutput)
}

func (i DomainCapabilitiesArgs) ToDomainCapabilitiesPtrOutput() DomainCapabilitiesPtrOutput {
	return i.ToDomainCapabilitiesPtrOutputWithContext(context.Background())
}

func (i DomainCapabilitiesArgs) ToDomainCapabilitiesPtrOutputWithContext(ctx context.Context) DomainCapabilitiesPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainCapabilitiesOutput).ToDomainCapabilitiesPtrOutputWithContext(ctx)
}

// DomainCapabilitiesPtrInput is an input type that accepts DomainCapabilitiesArgs, DomainCapabilitiesPtr and DomainCapabilitiesPtrOutput values.
// You can construct a concrete instance of `DomainCapabilitiesPtrInput` via:
//
//	        DomainCapabilitiesArgs{...}
//
//	or:
//
//	        nil
type DomainCapabilitiesPtrInput interface {
	pulumi.Input

	ToDomainCapabilitiesPtrOutput() DomainCapabilitiesPtrOutput
	ToDomainCapabilitiesPtrOutputWithContext(context.Context) DomainCapabilitiesPtrOutput
}

type domainCapabilitiesPtrType DomainCapabilitiesArgs

func DomainCapabilitiesPtr(v *DomainCapabilitiesArgs) DomainCapabilitiesPtrInput {
	return (*domainCapabilitiesPtrType)(v)
}

func (*domainCapabilitiesPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainCapabilities)(nil)).Elem()
}

func (i *domainCapabilitiesPtrType) ToDomainCapabilitiesPtrOutput() DomainCapabilitiesPtrOutput {
	return i.ToDomainCapabilitiesPtrOutputWithContext(context.Background())
}

func (i *domainCapabilitiesPtrType) ToDomainCapabilitiesPtrOutputWithContext(ctx context.Context) DomainCapabilitiesPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainCapabilitiesPtrOutput)
}

type DomainCapabilitiesOutput struct{ *pulumi.OutputState }

func (DomainCapabilitiesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainCapabilities)(nil)).Elem()
}

func (o DomainCapabilitiesOutput) ToDomainCapabilitiesOutput() DomainCapabilitiesOutput {
	return o
}

func (o DomainCapabilitiesOutput) ToDomainCapabilitiesOutputWithContext(ctx context.Context) DomainCapabilitiesOutput {
	return o
}

func (o DomainCapabilitiesOutput) ToDomainCapabilitiesPtrOutput() DomainCapabilitiesPtrOutput {
	return o.ToDomainCapabilitiesPtrOutputWithContext(context.Background())
}

func (o DomainCapabilitiesOutput) ToDomainCapabilitiesPtrOutputWithContext(ctx context.Context) DomainCapabilitiesPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DomainCapabilities) *DomainCapabilities {
		return &v
	}).(DomainCapabilitiesPtrOutput)
}

func (o DomainCapabilitiesOutput) Receiving() DomainCapabilityStatusPtrOutput {
	return o.ApplyT(func(v DomainCapabilities) *DomainCapabilityStatus { return v.Receiving }).(DomainCapabilityStatusPtrOutput)
}

func (o DomainCapabilitiesOutput) Sending() DomainCapabilityStatusPtrOutput {
	return o.ApplyT(func(v DomainCapabilities) *DomainCapabilityStatus { return v.Sending }).(DomainCapabilityStatusPtrOutput)
}

type DomainCapabilitiesPtrOutput struct{ *pulumi.OutputState }

func (DomainCapabilitiesPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainCapabilities)(nil)).Elem()
}

func (o DomainCapabilitiesPtrOutput) ToDomainCapabilitiesPtrOutput() DomainCapabilitiesPtrOutput {
	return o
}

func (o DomainCapabilitiesPtrOutput) ToDomainCapabilitiesPtrOutputWithContext(ctx context.Context) DomainCapabilitiesPtrOutput {
	return o
}

func (o DomainCapabilitiesPtrOutput) Elem() DomainCapabilitiesOutput {
	return o.ApplyT(func(v *DomainCapabilities) DomainCapabilities {
		if v != nil {
			return *v
		}
		var ret DomainCapabilities
		return ret
	}).(DomainCapabilitiesOutput)
}

func (o DomainCapabilitiesPtrOutput) Receiving() DomainCapabilityStatusPtrOutput {
	return o.ApplyT(func(v *DomainCapabilities) *DomainCapabilityStatus {
		if v == nil {
			return nil
		}
		return v.Receiving
	}).(DomainCapabilityStatusPtrOutput)
}

func (o DomainCapabilitiesPtrOutput) Sending() DomainCapabilityStatusPtrOutput {
	return o.ApplyT(func(v *DomainCapabilities) *DomainCapabilityStatus {
		if v == nil {
			return nil
		}
		return v.Sending
	}).(DomainCapabilityStatusPtrOutput)
}

type DomainRecord struct {
	Name     string  `pulumi:"name"`
	Priority *string `pulumi:"priority"`
	Record   string  `pulumi:"record"`
	Status   string  `pulumi:"status"`
	Ttl      string  `pulumi:"ttl"`
	Type     string  `pulumi:"type"`
	Value    string  `pulumi:"value"`
}

type DomainRecordOutput struct{ *pulumi.OutputState }

func (DomainRecordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainRecord)(nil)).Elem()
}

func (o DomainRecordOutput) ToDomainRecordOutput() DomainRecordOutput {
	return o
}

func (o DomainRecordOutput) ToDomainRecordOutputWithContext(ctx context.Context) DomainRecordOutput {
	return o
}

func (o DomainRecordOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v DomainRecord) string { return v.Name }).(pulumi.StringOutput)
}

func (o DomainRecordOutput) Priority() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DomainRecord) *string { return v.Priority }).(pulumi.StringPtrOutput)
}

func (o DomainRecordOutput) Record() pulumi.StringOutput {
	return o.ApplyT(func(v DomainRecord) string { return v.Record }).(pulumi.StringOutput)
}

func (o DomainRecordOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v DomainRecord) string { return v.Status }).(pulumi.StringOutput)
}

func (o DomainRecordOutput) Ttl() pulumi.StringOutput {
	return o.ApplyT(func(v DomainRecord) string { return v.Ttl }).(pulumi.StringOutput)
}

func (o DomainRecordOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v DomainRecord) string { return v.Type }).(pulumi.StringOutput)
}

func (o DomainRecordOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v DomainRecord) string { return v.Value }).(pulumi.StringOutput)
}

type DomainRecordArrayOutput struct{ *pulumi.OutputState }

func (DomainRecordArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DomainRecord)(nil)).Elem()
}

func (o DomainRecordArrayOutput) ToDomainRecordArrayOutput() DomainRecordArrayOutput {
	return o
}

func (o DomainRecordArrayOutput) ToDomainRecordArrayOutputWithContext(ctx context.Context) DomainRecordArrayOutput {
	return o
}

func (o DomainRecordArrayOutput) Index(i pulumi.IntInput) DomainRecordOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DomainRecord {
		return vs[0].([]DomainRecord)[vs[1].(int)]
	}).(DomainRecordOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainCapabilitiesInput)(nil)).Elem(), DomainCapabilitiesArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainCapabilitiesPtrInput)(nil)).Elem(), DomainCapabilitiesArgs{})
	pulumi.RegisterOutputType(DomainCapabilitiesOutput{})
	pulumi.RegisterOutputType(DomainCapabilitiesPtrOutput{})
	pulumi.RegisterOutputType(DomainRecordOutput{})
	pulumi.RegisterOutputType(DomainRecordArrayOutput{})
}
