// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend.outputs;

import com.iwahbe.resend.enums.DomainCapabilityStatus;
import com.pulumi.core.annotations.CustomType;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DomainCapabilities {
    private @Nullable DomainCapabilityStatus receiving;
    private @Nullable DomainCapabilityStatus sending;

    private DomainCapabilities() {}
    public Optional<DomainCapabilityStatus> receiving() {
        return Optional.ofNullable(this.receiving);
    }
    public Optional<DomainCapabilityStatus> sending() {
        return Optional.ofNullable(this.sending);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DomainCapabilities defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable DomainCapabilityStatus receiving;
        private @Nullable DomainCapabilityStatus sending;
        public Builder() {}
        public Builder(DomainCapabilities defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.receiving = defaults.receiving;
    	      this.sending = defaults.sending;
        }

        @CustomType.Setter
        public Builder receiving(@Nullable DomainCapabilityStatus receiving) {

            this.receiving = receiving;
            return this;
        }
        @CustomType.Setter
        public Builder sending(@Nullable DomainCapabilityStatus sending) {

            this.sending = sending;
            return this;
        }
        public DomainCapabilities build() {
            final var _resultValue = new DomainCapabilities();
            _resultValue.receiving = receiving;
            _resultValue.sending = sending;
            return _resultValue;
        }
    }
}
