// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DomainRecord {
    private String name;
    private @Nullable String priority;
    private String record;
    private String status;
    private String ttl;
    private String type;
    private String value;

    private DomainRecord() {}
    public String name() {
        return this.name;
    }
    public Optional<String> priority() {
        return Optional.ofNullable(this.priority);
    }
    public String record() {
        return this.record;
    }
    public String status() {
        return this.status;
    }
    public String ttl() {
        return this.ttl;
    }
    public String type() {
        return this.type;
    }
    public String value() {
        return this.value;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DomainRecord defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String name;
        private @Nullable String priority;
        private String record;
        private String status;
        private String ttl;
        private String type;
        private String value;
        public Builder() {}
        public Builder(DomainRecord defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.priority = defaults.priority;
    	      this.record = defaults.record;
    	      this.status = defaults.status;
    	      this.ttl = defaults.ttl;
    	      this.type = defaults.type;
    	      this.value = defaults.value;
        }

        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("DomainRecord", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder priority(@Nullable String priority) {

            this.priority = priority;
            return this;
        }
        @CustomType.Setter
        public Builder record(String record) {
            if (record == null) {
              throw new MissingRequiredPropertyException("DomainRecord", "record");
            }
            this.record = record;
            return this;
        }
        @CustomType.Setter
        public Builder status(String status) {
            if (status == null) {
              throw new MissingRequiredPropertyException("DomainRecord", "status");
            }
            this.status = status;
            return this;
        }
        @CustomType.Setter
        public Builder ttl(String ttl) {
            if (ttl == null) {
              throw new MissingRequiredPropertyException("DomainRecord", "ttl");
            }
            this.ttl = ttl;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("DomainRecord", "type");
            }
            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder value(String value) {
            if (value == null) {
              throw new MissingRequiredPropertyException("DomainRecord", "value");
            }
            this.value = value;
            return this;
        }
        public DomainRecord build() {
            final var _resultValue = new DomainRecord();
            _resultValue.name = name;
            _resultValue.priority = priority;
            _resultValue.record = record;
            _resultValue.status = status;
            _resultValue.ttl = ttl;
            _resultValue.type = type;
            _resultValue.value = value;
            return _resultValue;
        }
    }
}
