// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const ApiKeyPermission = {
    /**
     * Full access to the Resend API.
     */
    Full_access: "full_access",
    /**
     * Permission to send emails.
     */
    Sending_access: "sending_access",
} as const;

export type ApiKeyPermission = (typeof ApiKeyPermission)[keyof typeof ApiKeyPermission];

export const ContactPropertyType = {
    /**
     * A string contact property.
     */
    String: "string",
    /**
     * A numeric contact property.
     */
    Number: "number",
} as const;

export type ContactPropertyType = (typeof ContactPropertyType)[keyof typeof ContactPropertyType];

export const DomainCapabilityStatus = {
    Enabled: "enabled",
    Disabled: "disabled",
} as const;

export type DomainCapabilityStatus = (typeof DomainCapabilityStatus)[keyof typeof DomainCapabilityStatus];

export const DomainRegion = {
    Us_east_1: "us-east-1",
    Eu_west_1: "eu-west-1",
    Sa_east_1: "sa-east-1",
    Ap_northeast_1: "ap-northeast-1",
} as const;

export type DomainRegion = (typeof DomainRegion)[keyof typeof DomainRegion];

export const DomainTLS = {
    Enforced: "enforced",
    Opportunistic: "opportunistic",
} as const;

export type DomainTLS = (typeof DomainTLS)[keyof typeof DomainTLS];

export const TopicDefaultSubscription = {
    /**
     * Subscribe new contacts to this topic by default.
     */
    Opt_in: "opt_in",
    /**
     * Do not subscribe new contacts to this topic by default.
     */
    Opt_out: "opt_out",
} as const;

export type TopicDefaultSubscription = (typeof TopicDefaultSubscription)[keyof typeof TopicDefaultSubscription];

export const WebhookEvent = {
    Email_sent: "email.sent",
    Email_delivered: "email.delivered",
    Email_delivery_delayed: "email.delivery_delayed",
    Email_complained: "email.complained",
    Email_bounced: "email.bounced",
    Email_opened: "email.opened",
    Email_clicked: "email.clicked",
    Email_received: "email.received",
    Email_failed: "email.failed",
    Email_scheduled: "email.scheduled",
    Email_suppressed: "email.suppressed",
    Contact_created: "contact.created",
    Contact_updated: "contact.updated",
    Contact_deleted: "contact.deleted",
    Domain_created: "domain.created",
    Domain_updated: "domain.updated",
    Domain_deleted: "domain.deleted",
} as const;

export type WebhookEvent = (typeof WebhookEvent)[keyof typeof WebhookEvent];
