// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Iwahbe.Resend.Outputs
{

    [OutputType]
    public sealed class DomainCapabilities
    {
        public readonly Iwahbe.Resend.DomainCapabilityStatus? Receiving;
        public readonly Iwahbe.Resend.DomainCapabilityStatus? Sending;

        [OutputConstructor]
        private DomainCapabilities(
            Iwahbe.Resend.DomainCapabilityStatus? receiving,

            Iwahbe.Resend.DomainCapabilityStatus? sending)
        {
            Receiving = receiving;
            Sending = sending;
        }
    }
}
