// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Iwahbe.Resend.Outputs
{

    [OutputType]
    public sealed class DomainRecord
    {
        public readonly string Name;
        public readonly string? Priority;
        public readonly string Record;
        public readonly string Status;
        public readonly string Ttl;
        public readonly string Type;
        public readonly string Value;

        [OutputConstructor]
        private DomainRecord(
            string name,

            string? priority,

            string record,

            string status,

            string ttl,

            string type,

            string value)
        {
            Name = name;
            Priority = priority;
            Record = record;
            Status = status;
            Ttl = ttl;
            Type = type;
            Value = value;
        }
    }
}
