// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend.inputs;

import com.iwahbe.resend.enums.DomainCapabilityStatus;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainCapabilitiesArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainCapabilitiesArgs Empty = new DomainCapabilitiesArgs();

    @Import(name="receiving")
    private @Nullable Output<DomainCapabilityStatus> receiving;

    public Optional<Output<DomainCapabilityStatus>> receiving() {
        return Optional.ofNullable(this.receiving);
    }

    @Import(name="sending")
    private @Nullable Output<DomainCapabilityStatus> sending;

    public Optional<Output<DomainCapabilityStatus>> sending() {
        return Optional.ofNullable(this.sending);
    }

    private DomainCapabilitiesArgs() {}

    private DomainCapabilitiesArgs(DomainCapabilitiesArgs $) {
        this.receiving = $.receiving;
        this.sending = $.sending;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainCapabilitiesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainCapabilitiesArgs $;

        public Builder() {
            $ = new DomainCapabilitiesArgs();
        }

        public Builder(DomainCapabilitiesArgs defaults) {
            $ = new DomainCapabilitiesArgs(Objects.requireNonNull(defaults));
        }

        public Builder receiving(@Nullable Output<DomainCapabilityStatus> receiving) {
            $.receiving = receiving;
            return this;
        }

        public Builder receiving(DomainCapabilityStatus receiving) {
            return receiving(Output.of(receiving));
        }

        public Builder sending(@Nullable Output<DomainCapabilityStatus> sending) {
            $.sending = sending;
            return this;
        }

        public Builder sending(DomainCapabilityStatus sending) {
            return sending(Output.of(sending));
        }

        public DomainCapabilitiesArgs build() {
            return $;
        }
    }

}
