// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend.enums;

import com.pulumi.core.annotations.EnumType;
import java.lang.String;
import java.util.Objects;
import java.util.StringJoiner;

    @EnumType
    public enum ContactPropertyType {
        /**
         * A string contact property.
         * 
         */
        String("string"),
        /**
         * A numeric contact property.
         * 
         */
        Number("number");

        private final String value;

        ContactPropertyType(String value) {
            this.value = Objects.requireNonNull(value);
        }

        @EnumType.Converter
        public String getValue() {
            return this.value;
        }

        @Override
        public java.lang.String toString() {
            return new StringJoiner(", ", "ContactPropertyType[", "]")
                .add("value='" + this.value + "'")
                .toString();
        }
    }
