// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend.enums;

import com.pulumi.core.annotations.EnumType;
import java.lang.String;
import java.util.Objects;
import java.util.StringJoiner;

    @EnumType
    public enum DomainRegion {
        Useast1("us-east-1"),
        Euwest1("eu-west-1"),
        Saeast1("sa-east-1"),
        Apnortheast1("ap-northeast-1");

        private final String value;

        DomainRegion(String value) {
            this.value = Objects.requireNonNull(value);
        }

        @EnumType.Converter
        public String getValue() {
            return this.value;
        }

        @Override
        public java.lang.String toString() {
            return new StringJoiner(", ", "DomainRegion[", "]")
                .add("value='" + this.value + "'")
                .toString();
        }
    }
