// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend.enums;

import com.pulumi.core.annotations.EnumType;
import java.lang.String;
import java.util.Objects;
import java.util.StringJoiner;

    @EnumType
    public enum TopicDefaultSubscription {
        /**
         * Subscribe new contacts to this topic by default.
         * 
         */
        Opt_in("opt_in"),
        /**
         * Do not subscribe new contacts to this topic by default.
         * 
         */
        Opt_out("opt_out");

        private final String value;

        TopicDefaultSubscription(String value) {
            this.value = Objects.requireNonNull(value);
        }

        @EnumType.Converter
        public String getValue() {
            return this.value;
        }

        @Override
        public java.lang.String toString() {
            return new StringJoiner(", ", "TopicDefaultSubscription[", "]")
                .add("value='" + this.value + "'")
                .toString();
        }
    }
