// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend.enums;

import com.pulumi.core.annotations.EnumType;
import java.lang.String;
import java.util.Objects;
import java.util.StringJoiner;

    @EnumType
    public enum WebhookEvent {
        Email_sent("email.sent"),
        Email_delivered("email.delivered"),
        Email_delivery_delayed("email.delivery_delayed"),
        Email_complained("email.complained"),
        Email_bounced("email.bounced"),
        Email_opened("email.opened"),
        Email_clicked("email.clicked"),
        Email_received("email.received"),
        Email_failed("email.failed"),
        Email_scheduled("email.scheduled"),
        Email_suppressed("email.suppressed"),
        Contact_created("contact.created"),
        Contact_updated("contact.updated"),
        Contact_deleted("contact.deleted"),
        Domain_created("domain.created"),
        Domain_updated("domain.updated"),
        Domain_deleted("domain.deleted");

        private final String value;

        WebhookEvent(String value) {
            this.value = Objects.requireNonNull(value);
        }

        @EnumType.Converter
        public String getValue() {
            return this.value;
        }

        @Override
        public java.lang.String toString() {
            return new StringJoiner(", ", "WebhookEvent[", "]")
                .add("value='" + this.value + "'")
                .toString();
        }
    }
