# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .api_key import *
from .contact_property import *
from .domain import *
from .domain_verification import *
from .provider import *
from .segment import *
from .topic import *
from .webhook import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import iwahbe_resend.config as __config
    config = __config
else:
    config = _utilities.lazy_import('iwahbe_resend.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "resend",
  "mod": "index",
  "fqn": "iwahbe_resend",
  "classes": {
   "resend:index:ApiKey": "ApiKey",
   "resend:index:ContactProperty": "ContactProperty",
   "resend:index:Domain": "Domain",
   "resend:index:DomainVerification": "DomainVerification",
   "resend:index:Segment": "Segment",
   "resend:index:Topic": "Topic",
   "resend:index:Webhook": "Webhook"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "resend",
  "token": "pulumi:providers:resend",
  "fqn": "iwahbe_resend",
  "class": "Provider"
 }
]
"""
)
