# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'ApiKeyPermission',
    'ContactPropertyType',
    'DomainCapabilityStatus',
    'DomainRegion',
    'DomainTLS',
    'TopicDefaultSubscription',
    'WebhookEvent',
]


@pulumi.type_token("resend:index:ApiKeyPermission")
class ApiKeyPermission(_builtins.str, Enum):
    FULL_ACCESS = "full_access"
    """
    Full access to the Resend API.
    """
    SENDING_ACCESS = "sending_access"
    """
    Permission to send emails.
    """


@pulumi.type_token("resend:index:ContactPropertyType")
class ContactPropertyType(_builtins.str, Enum):
    STRING = "string"
    """
    A string contact property.
    """
    NUMBER = "number"
    """
    A numeric contact property.
    """


@pulumi.type_token("resend:index:DomainCapabilityStatus")
class DomainCapabilityStatus(_builtins.str, Enum):
    ENABLED = "enabled"
    DISABLED = "disabled"


@pulumi.type_token("resend:index:DomainRegion")
class DomainRegion(_builtins.str, Enum):
    US_EAST_1 = "us-east-1"
    EU_WEST_1 = "eu-west-1"
    SA_EAST_1 = "sa-east-1"
    AP_NORTHEAST_1 = "ap-northeast-1"


@pulumi.type_token("resend:index:DomainTLS")
class DomainTLS(_builtins.str, Enum):
    ENFORCED = "enforced"
    OPPORTUNISTIC = "opportunistic"


@pulumi.type_token("resend:index:TopicDefaultSubscription")
class TopicDefaultSubscription(_builtins.str, Enum):
    OPT_IN = "opt_in"
    """
    Subscribe new contacts to this topic by default.
    """
    OPT_OUT = "opt_out"
    """
    Do not subscribe new contacts to this topic by default.
    """


@pulumi.type_token("resend:index:WebhookEvent")
class WebhookEvent(_builtins.str, Enum):
    EMAIL_SENT = "email.sent"
    EMAIL_DELIVERED = "email.delivered"
    EMAIL_DELIVERY_DELAYED = "email.delivery_delayed"
    EMAIL_COMPLAINED = "email.complained"
    EMAIL_BOUNCED = "email.bounced"
    EMAIL_OPENED = "email.opened"
    EMAIL_CLICKED = "email.clicked"
    EMAIL_RECEIVED = "email.received"
    EMAIL_FAILED = "email.failed"
    EMAIL_SCHEDULED = "email.scheduled"
    EMAIL_SUPPRESSED = "email.suppressed"
    CONTACT_CREATED = "contact.created"
    CONTACT_UPDATED = "contact.updated"
    CONTACT_DELETED = "contact.deleted"
    DOMAIN_CREATED = "domain.created"
    DOMAIN_UPDATED = "domain.updated"
    DOMAIN_DELETED = "domain.deleted"
