# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = [
    'DomainCapabilitiesArgs',
    'DomainCapabilitiesArgsDict',
]

class DomainCapabilitiesArgsDict(TypedDict):
    receiving: NotRequired[pulumi.Input[Optional['DomainCapabilityStatus']]]
    sending: NotRequired[pulumi.Input[Optional['DomainCapabilityStatus']]]

@pulumi.input_type
class DomainCapabilitiesArgs:
    def __init__(__self__, *,
                 receiving: pulumi.Input[Optional['DomainCapabilityStatus']] = None,
                 sending: pulumi.Input[Optional['DomainCapabilityStatus']] = None):
        if receiving is not None:
            pulumi.set(__self__, "receiving", receiving)
        if sending is not None:
            pulumi.set(__self__, "sending", sending)

    @_builtins.property
    @pulumi.getter
    def receiving(self) -> pulumi.Input[Optional['DomainCapabilityStatus']]:
        return pulumi.get(self, "receiving")

    @receiving.setter
    def receiving(self, value: pulumi.Input[Optional['DomainCapabilityStatus']]):
        pulumi.set(self, "receiving", value)

    @_builtins.property
    @pulumi.getter
    def sending(self) -> pulumi.Input[Optional['DomainCapabilityStatus']]:
        return pulumi.get(self, "sending")

    @sending.setter
    def sending(self, value: pulumi.Input[Optional['DomainCapabilityStatus']]):
        pulumi.set(self, "sending", value)


