# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = ['ContactPropertyArgs', 'ContactProperty']

@pulumi.input_type
class ContactPropertyArgs:
    def __init__(__self__, *,
                 key: pulumi.Input[_builtins.str],
                 type: pulumi.Input['ContactPropertyType'],
                 fallback_value: Optional[Any] = None):
        """
        The set of arguments for constructing a ContactProperty resource.

        :param pulumi.Input[_builtins.str] key: The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
        :param pulumi.Input['ContactPropertyType'] type: The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
        :param Any fallback_value: Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
        """
        pulumi.set(__self__, "key", key)
        pulumi.set(__self__, "type", type)
        if fallback_value is not None:
            pulumi.set(__self__, "fallback_value", fallback_value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Input[_builtins.str]:
        """
        The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input['ContactPropertyType']:
        """
        The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input['ContactPropertyType']):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="fallbackValue")
    def fallback_value(self) -> Optional[Any]:
        """
        Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
        """
        return pulumi.get(self, "fallback_value")

    @fallback_value.setter
    def fallback_value(self, value: Optional[Any]):
        pulumi.set(self, "fallback_value", value)


@pulumi.type_token("resend:index:ContactProperty")
class ContactProperty(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 fallback_value: Optional[Any] = None,
                 key: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional['ContactPropertyType']] = None,
                 __props__=None):
        """
        A Resend custom contact property definition.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param Any fallback_value: Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
        :param pulumi.Input[_builtins.str] key: The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
        :param pulumi.Input['ContactPropertyType'] type: The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ContactPropertyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A Resend custom contact property definition.

        :param str resource_name: The name of the resource.
        :param ContactPropertyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ContactPropertyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 fallback_value: Optional[Any] = None,
                 key: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional['ContactPropertyType']] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ContactPropertyArgs.__new__(ContactPropertyArgs)

            __props__.__dict__["fallback_value"] = fallback_value
            if key is None and not opts.urn:
                raise TypeError("Missing required property 'key'")
            __props__.__dict__["key"] = key
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            __props__.__dict__["created_at"] = None
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["key", "type"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(ContactProperty, __self__).__init__(
            'resend:index:ContactProperty',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'ContactProperty':
        """
        Get an existing ContactProperty resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ContactPropertyArgs.__new__(ContactPropertyArgs)

        __props__.__dict__["created_at"] = None
        __props__.__dict__["fallback_value"] = None
        __props__.__dict__["key"] = None
        __props__.__dict__["type"] = None
        return ContactProperty(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        The timestamp when Resend created the contact property, as returned by the Resend API `created_at` string.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="fallbackValue")
    def fallback_value(self) -> pulumi.Output[Optional[Any]]:
        """
        Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
        """
        return pulumi.get(self, "fallback_value")

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Output[_builtins.str]:
        """
        The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output['ContactPropertyType']:
        """
        The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
        """
        return pulumi.get(self, "type")

