# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._enums import *
from ._inputs import *

__all__ = ['DomainArgs', 'Domain']

@pulumi.input_type
class DomainArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 capabilities: pulumi.Input[Optional['DomainCapabilitiesArgs']] = None,
                 click_tracking: pulumi.Input[Optional[_builtins.bool]] = None,
                 custom_return_path: pulumi.Input[Optional[_builtins.str]] = None,
                 open_tracking: pulumi.Input[Optional[_builtins.bool]] = None,
                 region: pulumi.Input[Optional['DomainRegion']] = None,
                 tls: pulumi.Input[Optional['DomainTLS']] = None,
                 tracking_subdomain: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Domain resource.

        :param pulumi.Input[_builtins.str] name: The domain name, e.g. `example.com`.
        :param pulumi.Input['DomainCapabilitiesArgs'] capabilities: Enable `sending` and/or `receiving` for this domain.
        :param pulumi.Input[_builtins.bool] click_tracking: Track link clicks in HTML emails. Requires a verified tracking subdomain.
        :param pulumi.Input[_builtins.str] custom_return_path: The subdomain used for the Return-Path address. Defaults to `send`.
        :param pulumi.Input[_builtins.bool] open_tracking: Track email open rates. Requires a verified tracking subdomain.
        :param pulumi.Input['DomainRegion'] region: The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
        :param pulumi.Input['DomainTLS'] tls: Connection encryption: `opportunistic` (default) or `enforced`.
        :param pulumi.Input[_builtins.str] tracking_subdomain: Custom subdomain used for open/click tracking links.
        """
        pulumi.set(__self__, "name", name)
        if capabilities is not None:
            pulumi.set(__self__, "capabilities", capabilities)
        if click_tracking is not None:
            pulumi.set(__self__, "click_tracking", click_tracking)
        if custom_return_path is not None:
            pulumi.set(__self__, "custom_return_path", custom_return_path)
        if open_tracking is not None:
            pulumi.set(__self__, "open_tracking", open_tracking)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if tls is not None:
            pulumi.set(__self__, "tls", tls)
        if tracking_subdomain is not None:
            pulumi.set(__self__, "tracking_subdomain", tracking_subdomain)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The domain name, e.g. `example.com`.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> pulumi.Input[Optional['DomainCapabilitiesArgs']]:
        """
        Enable `sending` and/or `receiving` for this domain.
        """
        return pulumi.get(self, "capabilities")

    @capabilities.setter
    def capabilities(self, value: pulumi.Input[Optional['DomainCapabilitiesArgs']]):
        pulumi.set(self, "capabilities", value)

    @_builtins.property
    @pulumi.getter(name="clickTracking")
    def click_tracking(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Track link clicks in HTML emails. Requires a verified tracking subdomain.
        """
        return pulumi.get(self, "click_tracking")

    @click_tracking.setter
    def click_tracking(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "click_tracking", value)

    @_builtins.property
    @pulumi.getter(name="customReturnPath")
    def custom_return_path(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The subdomain used for the Return-Path address. Defaults to `send`.
        """
        return pulumi.get(self, "custom_return_path")

    @custom_return_path.setter
    def custom_return_path(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "custom_return_path", value)

    @_builtins.property
    @pulumi.getter(name="openTracking")
    def open_tracking(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Track email open rates. Requires a verified tracking subdomain.
        """
        return pulumi.get(self, "open_tracking")

    @open_tracking.setter
    def open_tracking(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "open_tracking", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[Optional['DomainRegion']]:
        """
        The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[Optional['DomainRegion']]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter
    def tls(self) -> pulumi.Input[Optional['DomainTLS']]:
        """
        Connection encryption: `opportunistic` (default) or `enforced`.
        """
        return pulumi.get(self, "tls")

    @tls.setter
    def tls(self, value: pulumi.Input[Optional['DomainTLS']]):
        pulumi.set(self, "tls", value)

    @_builtins.property
    @pulumi.getter(name="trackingSubdomain")
    def tracking_subdomain(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Custom subdomain used for open/click tracking links.
        """
        return pulumi.get(self, "tracking_subdomain")

    @tracking_subdomain.setter
    def tracking_subdomain(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "tracking_subdomain", value)


@pulumi.type_token("resend:index:Domain")
class Domain(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 capabilities: pulumi.Input[Optional[Union['DomainCapabilitiesArgs', 'DomainCapabilitiesArgsDict']]] = None,
                 click_tracking: pulumi.Input[Optional[_builtins.bool]] = None,
                 custom_return_path: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 open_tracking: pulumi.Input[Optional[_builtins.bool]] = None,
                 region: pulumi.Input[Optional['DomainRegion']] = None,
                 tls: pulumi.Input[Optional['DomainTLS']] = None,
                 tracking_subdomain: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A domain registered with Resend for sending (and optionally receiving) email. The `records` output contains the DNS records that must be created before the domain can be verified.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['DomainCapabilitiesArgs', 'DomainCapabilitiesArgsDict']] capabilities: Enable `sending` and/or `receiving` for this domain.
        :param pulumi.Input[_builtins.bool] click_tracking: Track link clicks in HTML emails. Requires a verified tracking subdomain.
        :param pulumi.Input[_builtins.str] custom_return_path: The subdomain used for the Return-Path address. Defaults to `send`.
        :param pulumi.Input[_builtins.str] name: The domain name, e.g. `example.com`.
        :param pulumi.Input[_builtins.bool] open_tracking: Track email open rates. Requires a verified tracking subdomain.
        :param pulumi.Input['DomainRegion'] region: The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
        :param pulumi.Input['DomainTLS'] tls: Connection encryption: `opportunistic` (default) or `enforced`.
        :param pulumi.Input[_builtins.str] tracking_subdomain: Custom subdomain used for open/click tracking links.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DomainArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A domain registered with Resend for sending (and optionally receiving) email. The `records` output contains the DNS records that must be created before the domain can be verified.

        :param str resource_name: The name of the resource.
        :param DomainArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DomainArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 capabilities: pulumi.Input[Optional[Union['DomainCapabilitiesArgs', 'DomainCapabilitiesArgsDict']]] = None,
                 click_tracking: pulumi.Input[Optional[_builtins.bool]] = None,
                 custom_return_path: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 open_tracking: pulumi.Input[Optional[_builtins.bool]] = None,
                 region: pulumi.Input[Optional['DomainRegion']] = None,
                 tls: pulumi.Input[Optional['DomainTLS']] = None,
                 tracking_subdomain: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DomainArgs.__new__(DomainArgs)

            __props__.__dict__["capabilities"] = capabilities
            __props__.__dict__["click_tracking"] = click_tracking
            __props__.__dict__["custom_return_path"] = custom_return_path
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["open_tracking"] = open_tracking
            __props__.__dict__["region"] = region
            __props__.__dict__["tls"] = tls
            __props__.__dict__["tracking_subdomain"] = tracking_subdomain
            __props__.__dict__["created_at"] = None
            __props__.__dict__["records"] = None
            __props__.__dict__["status"] = None
        super(Domain, __self__).__init__(
            'resend:index:Domain',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Domain':
        """
        Get an existing Domain resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = DomainArgs.__new__(DomainArgs)

        __props__.__dict__["capabilities"] = None
        __props__.__dict__["click_tracking"] = None
        __props__.__dict__["created_at"] = None
        __props__.__dict__["custom_return_path"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["open_tracking"] = None
        __props__.__dict__["records"] = None
        __props__.__dict__["region"] = None
        __props__.__dict__["status"] = None
        __props__.__dict__["tls"] = None
        __props__.__dict__["tracking_subdomain"] = None
        return Domain(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> pulumi.Output[Optional['outputs.DomainCapabilities']]:
        """
        Enable `sending` and/or `receiving` for this domain.
        """
        return pulumi.get(self, "capabilities")

    @_builtins.property
    @pulumi.getter(name="clickTracking")
    def click_tracking(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Track link clicks in HTML emails. Requires a verified tracking subdomain.
        """
        return pulumi.get(self, "click_tracking")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="customReturnPath")
    def custom_return_path(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The subdomain used for the Return-Path address. Defaults to `send`.
        """
        return pulumi.get(self, "custom_return_path")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The domain name, e.g. `example.com`.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="openTracking")
    def open_tracking(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Track email open rates. Requires a verified tracking subdomain.
        """
        return pulumi.get(self, "open_tracking")

    @_builtins.property
    @pulumi.getter
    def records(self) -> pulumi.Output[Sequence['outputs.DomainRecord']]:
        """
        The DNS records to create for this domain.
        """
        return pulumi.get(self, "records")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[Optional['DomainRegion']]:
        """
        The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        The verification status of the domain.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def tls(self) -> pulumi.Output[Optional['DomainTLS']]:
        """
        Connection encryption: `opportunistic` (default) or `enforced`.
        """
        return pulumi.get(self, "tls")

    @_builtins.property
    @pulumi.getter(name="trackingSubdomain")
    def tracking_subdomain(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Custom subdomain used for open/click tracking links.
        """
        return pulumi.get(self, "tracking_subdomain")

