# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = [
    'DomainCapabilities',
    'DomainRecord',
]

@pulumi.output_type
class DomainCapabilities(dict):
    def __init__(__self__, *,
                 receiving: Optional['DomainCapabilityStatus'] = None,
                 sending: Optional['DomainCapabilityStatus'] = None):
        if receiving is not None:
            pulumi.set(__self__, "receiving", receiving)
        if sending is not None:
            pulumi.set(__self__, "sending", sending)

    @_builtins.property
    @pulumi.getter
    def receiving(self) -> Optional['DomainCapabilityStatus']:
        return pulumi.get(self, "receiving")

    @_builtins.property
    @pulumi.getter
    def sending(self) -> Optional['DomainCapabilityStatus']:
        return pulumi.get(self, "sending")


@pulumi.output_type
class DomainRecord(dict):
    def __init__(__self__, *,
                 name: _builtins.str,
                 record: _builtins.str,
                 status: _builtins.str,
                 ttl: _builtins.str,
                 type: _builtins.str,
                 value: _builtins.str,
                 priority: Optional[_builtins.str] = None):
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "record", record)
        pulumi.set(__self__, "status", status)
        pulumi.set(__self__, "ttl", ttl)
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "value", value)
        if priority is not None:
            pulumi.set(__self__, "priority", priority)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def record(self) -> _builtins.str:
        return pulumi.get(self, "record")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def ttl(self) -> _builtins.str:
        return pulumi.get(self, "ttl")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def value(self) -> _builtins.str:
        return pulumi.get(self, "value")

    @_builtins.property
    @pulumi.getter
    def priority(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "priority")


