# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = ['TopicArgs', 'Topic']

@pulumi.input_type
class TopicArgs:
    def __init__(__self__, *,
                 default_subscription: pulumi.Input['TopicDefaultSubscription'],
                 name: pulumi.Input[_builtins.str],
                 description: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Topic resource.

        :param pulumi.Input['TopicDefaultSubscription'] default_subscription: The default subscription preference for new contacts, either `opt_in` or `opt_out`. Resend does not allow this value to change after creation, so changes replace the topic.
        :param pulumi.Input[_builtins.str] name: The topic name.
        :param pulumi.Input[_builtins.str] description: An optional topic description. Non-empty values are sent to Resend on create and update. Because resend-go v4.2.0 omits empty `description` values from update requests, clearing an existing description replaces the topic.
        """
        pulumi.set(__self__, "default_subscription", default_subscription)
        pulumi.set(__self__, "name", name)
        if description is not None:
            pulumi.set(__self__, "description", description)

    @_builtins.property
    @pulumi.getter(name="defaultSubscription")
    def default_subscription(self) -> pulumi.Input['TopicDefaultSubscription']:
        """
        The default subscription preference for new contacts, either `opt_in` or `opt_out`. Resend does not allow this value to change after creation, so changes replace the topic.
        """
        return pulumi.get(self, "default_subscription")

    @default_subscription.setter
    def default_subscription(self, value: pulumi.Input['TopicDefaultSubscription']):
        pulumi.set(self, "default_subscription", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The topic name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        An optional topic description. Non-empty values are sent to Resend on create and update. Because resend-go v4.2.0 omits empty `description` values from update requests, clearing an existing description replaces the topic.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)


@pulumi.type_token("resend:index:Topic")
class Topic(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 default_subscription: pulumi.Input[Optional['TopicDefaultSubscription']] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A Resend broadcast topic used to manage contact subscription preferences.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input['TopicDefaultSubscription'] default_subscription: The default subscription preference for new contacts, either `opt_in` or `opt_out`. Resend does not allow this value to change after creation, so changes replace the topic.
        :param pulumi.Input[_builtins.str] description: An optional topic description. Non-empty values are sent to Resend on create and update. Because resend-go v4.2.0 omits empty `description` values from update requests, clearing an existing description replaces the topic.
        :param pulumi.Input[_builtins.str] name: The topic name.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: TopicArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A Resend broadcast topic used to manage contact subscription preferences.

        :param str resource_name: The name of the resource.
        :param TopicArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TopicArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 default_subscription: pulumi.Input[Optional['TopicDefaultSubscription']] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TopicArgs.__new__(TopicArgs)

            if default_subscription is None and not opts.urn:
                raise TypeError("Missing required property 'default_subscription'")
            __props__.__dict__["default_subscription"] = default_subscription
            __props__.__dict__["description"] = description
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["created_at"] = None
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["defaultSubscription"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(Topic, __self__).__init__(
            'resend:index:Topic',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Topic':
        """
        Get an existing Topic resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = TopicArgs.__new__(TopicArgs)

        __props__.__dict__["created_at"] = None
        __props__.__dict__["default_subscription"] = None
        __props__.__dict__["description"] = None
        __props__.__dict__["name"] = None
        return Topic(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        The timestamp when Resend created the topic, as returned by the Resend API `created_at` string in `YYYY-MM-DD HH:MM:SS.ffffff+00` format (for example, `2023-04-08 00:11:13.110779+00`).
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="defaultSubscription")
    def default_subscription(self) -> pulumi.Output['TopicDefaultSubscription']:
        """
        The default subscription preference for new contacts, either `opt_in` or `opt_out`. Resend does not allow this value to change after creation, so changes replace the topic.
        """
        return pulumi.get(self, "default_subscription")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        An optional topic description. Non-empty values are sent to Resend on create and update. Because resend-go v4.2.0 omits empty `description` values from update requests, clearing an existing description replaces the topic.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The topic name.
        """
        return pulumi.get(self, "name")

