// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface DomainCapabilities {
    receiving?: enums.DomainCapabilityStatus;
    sending?: enums.DomainCapabilityStatus;
}

export interface DomainRecord {
    name: string;
    priority?: string;
    record: string;
    status: string;
    ttl: string;
    type: string;
    value: string;
}

