// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/iwahbe/pulumi-resend/sdk/go/resend/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The Resend API key. Defaults to the value of the `RESEND_API_KEY` environment variable.
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "resend:apiKey")
}
