// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Iwahbe.Resend.Inputs
{

    public sealed class DomainCapabilitiesArgs : global::Pulumi.ResourceArgs
    {
        [Input("receiving")]
        public Input<Iwahbe.Resend.DomainCapabilityStatus>? Receiving { get; set; }

        [Input("sending")]
        public Input<Iwahbe.Resend.DomainCapabilityStatus>? Sending { get; set; }

        public DomainCapabilitiesArgs()
        {
        }
        public static new DomainCapabilitiesArgs Empty => new DomainCapabilitiesArgs();
    }
}
