// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend;

import com.iwahbe.resend.ApiKeyArgs;
import com.iwahbe.resend.Utilities;
import com.iwahbe.resend.enums.ApiKeyPermission;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A Resend API key. The `token` output is only available from the Resend API at creation time; it cannot be recovered later.
 * 
 */
@ResourceType(type="resend:index:ApiKey")
public class ApiKey extends com.pulumi.resources.CustomResource {
    /**
     * Restrict a `sending_access` key to a single domain.
     * 
     */
    @Export(name="domainId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> domainId;

    /**
     * @return Restrict a `sending_access` key to a single domain.
     * 
     */
    public Output<Optional<String>> domainId() {
        return Codegen.optional(this.domainId);
    }
    /**
     * The API key name. Maximum 50 characters.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The API key name. Maximum 50 characters.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * `full_access` or `sending_access`.
     * 
     */
    @Export(name="permission", refs={ApiKeyPermission.class}, tree="[0]")
    private Output</* @Nullable */ ApiKeyPermission> permission;

    /**
     * @return `full_access` or `sending_access`.
     * 
     */
    public Output<Optional<ApiKeyPermission>> permission() {
        return Codegen.optional(this.permission);
    }
    /**
     * The API key credential. Only returned by Resend at creation time; empty after import.
     * 
     */
    @Export(name="token", refs={String.class}, tree="[0]")
    private Output<String> token;

    /**
     * @return The API key credential. Only returned by Resend at creation time; empty after import.
     * 
     */
    public Output<String> token() {
        return this.token;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ApiKey(java.lang.String name) {
        this(name, ApiKeyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ApiKey(java.lang.String name, ApiKeyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ApiKey(java.lang.String name, ApiKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("resend:index:ApiKey", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ApiKey(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("resend:index:ApiKey", name, null, makeResourceOptions(options, id), false);
    }

    private static ApiKeyArgs makeArgs(ApiKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ApiKeyArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/iwahbe/pulumi-resend")
            .additionalSecretOutputs(List.of(
                "token"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ApiKey get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ApiKey(name, id, options);
    }
}
