// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend;

import com.iwahbe.resend.enums.ApiKeyPermission;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ApiKeyArgs extends com.pulumi.resources.ResourceArgs {

    public static final ApiKeyArgs Empty = new ApiKeyArgs();

    /**
     * Restrict a `sending_access` key to a single domain.
     * 
     */
    @Import(name="domainId")
    private @Nullable Output<String> domainId;

    /**
     * @return Restrict a `sending_access` key to a single domain.
     * 
     */
    public Optional<Output<String>> domainId() {
        return Optional.ofNullable(this.domainId);
    }

    /**
     * The API key name. Maximum 50 characters.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The API key name. Maximum 50 characters.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * `full_access` or `sending_access`.
     * 
     */
    @Import(name="permission")
    private @Nullable Output<ApiKeyPermission> permission;

    /**
     * @return `full_access` or `sending_access`.
     * 
     */
    public Optional<Output<ApiKeyPermission>> permission() {
        return Optional.ofNullable(this.permission);
    }

    private ApiKeyArgs() {}

    private ApiKeyArgs(ApiKeyArgs $) {
        this.domainId = $.domainId;
        this.name = $.name;
        this.permission = $.permission;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ApiKeyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ApiKeyArgs $;

        public Builder() {
            $ = new ApiKeyArgs();
        }

        public Builder(ApiKeyArgs defaults) {
            $ = new ApiKeyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param domainId Restrict a `sending_access` key to a single domain.
         * 
         * @return builder
         * 
         */
        public Builder domainId(@Nullable Output<String> domainId) {
            $.domainId = domainId;
            return this;
        }

        /**
         * @param domainId Restrict a `sending_access` key to a single domain.
         * 
         * @return builder
         * 
         */
        public Builder domainId(String domainId) {
            return domainId(Output.of(domainId));
        }

        /**
         * @param name The API key name. Maximum 50 characters.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The API key name. Maximum 50 characters.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param permission `full_access` or `sending_access`.
         * 
         * @return builder
         * 
         */
        public Builder permission(@Nullable Output<ApiKeyPermission> permission) {
            $.permission = permission;
            return this;
        }

        /**
         * @param permission `full_access` or `sending_access`.
         * 
         * @return builder
         * 
         */
        public Builder permission(ApiKeyPermission permission) {
            return permission(Output.of(permission));
        }

        public ApiKeyArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("ApiKeyArgs", "name");
            }
            return $;
        }
    }

}
