// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend;

import com.iwahbe.resend.ContactPropertyArgs;
import com.iwahbe.resend.Utilities;
import com.iwahbe.resend.enums.ContactPropertyType;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A Resend custom contact property definition.
 * 
 */
@ResourceType(type="resend:index:ContactProperty")
public class ContactProperty extends com.pulumi.resources.CustomResource {
    /**
     * The timestamp when Resend created the contact property, as returned by the Resend API `created_at` string.
     * 
     */
    @Export(name="createdAt", refs={String.class}, tree="[0]")
    private Output<String> createdAt;

    /**
     * @return The timestamp when Resend created the contact property, as returned by the Resend API `created_at` string.
     * 
     */
    public Output<String> createdAt() {
        return this.createdAt;
    }
    /**
     * Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
     * 
     */
    @Export(name="fallbackValue", refs={Object.class}, tree="[0]")
    private Output</* @Nullable */ Object> fallbackValue;

    /**
     * @return Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
     * 
     */
    public Output<Optional<Object>> fallbackValue() {
        return Codegen.optional(this.fallbackValue);
    }
    /**
     * The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
     * 
     */
    @Export(name="key", refs={String.class}, tree="[0]")
    private Output<String> key;

    /**
     * @return The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
     * 
     */
    public Output<String> key() {
        return this.key;
    }
    /**
     * The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
     * 
     */
    @Export(name="type", refs={ContactPropertyType.class}, tree="[0]")
    private Output<ContactPropertyType> type;

    /**
     * @return The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
     * 
     */
    public Output<ContactPropertyType> type() {
        return this.type;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ContactProperty(java.lang.String name) {
        this(name, ContactPropertyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ContactProperty(java.lang.String name, ContactPropertyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ContactProperty(java.lang.String name, ContactPropertyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("resend:index:ContactProperty", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ContactProperty(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("resend:index:ContactProperty", name, null, makeResourceOptions(options, id), false);
    }

    private static ContactPropertyArgs makeArgs(ContactPropertyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ContactPropertyArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/iwahbe/pulumi-resend")
            .replaceOnChanges(List.of(
                "key",
                "type"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ContactProperty get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ContactProperty(name, id, options);
    }
}
