// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend;

import com.iwahbe.resend.enums.ContactPropertyType;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ContactPropertyArgs extends com.pulumi.resources.ResourceArgs {

    public static final ContactPropertyArgs Empty = new ContactPropertyArgs();

    /**
     * Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
     * 
     */
    @Import(name="fallbackValue")
    private @Nullable Output<Object> fallbackValue;

    /**
     * @return Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
     * 
     */
    public Optional<Output<Object>> fallbackValue() {
        return Optional.ofNullable(this.fallbackValue);
    }

    /**
     * The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
     * 
     */
    @Import(name="key", required=true)
    private Output<String> key;

    /**
     * @return The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
     * 
     */
    public Output<String> key() {
        return this.key;
    }

    /**
     * The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
     * 
     */
    @Import(name="type", required=true)
    private Output<ContactPropertyType> type;

    /**
     * @return The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
     * 
     */
    public Output<ContactPropertyType> type() {
        return this.type;
    }

    private ContactPropertyArgs() {}

    private ContactPropertyArgs(ContactPropertyArgs $) {
        this.fallbackValue = $.fallbackValue;
        this.key = $.key;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContactPropertyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContactPropertyArgs $;

        public Builder() {
            $ = new ContactPropertyArgs();
        }

        public Builder(ContactPropertyArgs defaults) {
            $ = new ContactPropertyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param fallbackValue Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
         * 
         * @return builder
         * 
         */
        public Builder fallbackValue(@Nullable Output<Object> fallbackValue) {
            $.fallbackValue = fallbackValue;
            return this;
        }

        /**
         * @param fallbackValue Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
         * 
         * @return builder
         * 
         */
        public Builder fallbackValue(Object fallbackValue) {
            return fallbackValue(Output.of(fallbackValue));
        }

        /**
         * @param key The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
         * 
         * @return builder
         * 
         */
        public Builder key(Output<String> key) {
            $.key = key;
            return this;
        }

        /**
         * @param key The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
         * 
         * @return builder
         * 
         */
        public Builder key(String key) {
            return key(Output.of(key));
        }

        /**
         * @param type The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
         * 
         * @return builder
         * 
         */
        public Builder type(Output<ContactPropertyType> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
         * 
         * @return builder
         * 
         */
        public Builder type(ContactPropertyType type) {
            return type(Output.of(type));
        }

        public ContactPropertyArgs build() {
            if ($.key == null) {
                throw new MissingRequiredPropertyException("ContactPropertyArgs", "key");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("ContactPropertyArgs", "type");
            }
            return $;
        }
    }

}
