// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend;

import com.iwahbe.resend.enums.DomainRegion;
import com.iwahbe.resend.enums.DomainTLS;
import com.iwahbe.resend.inputs.DomainCapabilitiesArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainArgs Empty = new DomainArgs();

    /**
     * Enable `sending` and/or `receiving` for this domain.
     * 
     */
    @Import(name="capabilities")
    private @Nullable Output<DomainCapabilitiesArgs> capabilities;

    /**
     * @return Enable `sending` and/or `receiving` for this domain.
     * 
     */
    public Optional<Output<DomainCapabilitiesArgs>> capabilities() {
        return Optional.ofNullable(this.capabilities);
    }

    /**
     * Track link clicks in HTML emails. Requires a verified tracking subdomain.
     * 
     */
    @Import(name="clickTracking")
    private @Nullable Output<Boolean> clickTracking;

    /**
     * @return Track link clicks in HTML emails. Requires a verified tracking subdomain.
     * 
     */
    public Optional<Output<Boolean>> clickTracking() {
        return Optional.ofNullable(this.clickTracking);
    }

    /**
     * The subdomain used for the Return-Path address. Defaults to `send`.
     * 
     */
    @Import(name="customReturnPath")
    private @Nullable Output<String> customReturnPath;

    /**
     * @return The subdomain used for the Return-Path address. Defaults to `send`.
     * 
     */
    public Optional<Output<String>> customReturnPath() {
        return Optional.ofNullable(this.customReturnPath);
    }

    /**
     * The domain name, e.g. `example.com`.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The domain name, e.g. `example.com`.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Track email open rates. Requires a verified tracking subdomain.
     * 
     */
    @Import(name="openTracking")
    private @Nullable Output<Boolean> openTracking;

    /**
     * @return Track email open rates. Requires a verified tracking subdomain.
     * 
     */
    public Optional<Output<Boolean>> openTracking() {
        return Optional.ofNullable(this.openTracking);
    }

    /**
     * The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
     * 
     */
    @Import(name="region")
    private @Nullable Output<DomainRegion> region;

    /**
     * @return The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
     * 
     */
    public Optional<Output<DomainRegion>> region() {
        return Optional.ofNullable(this.region);
    }

    /**
     * Connection encryption: `opportunistic` (default) or `enforced`.
     * 
     */
    @Import(name="tls")
    private @Nullable Output<DomainTLS> tls;

    /**
     * @return Connection encryption: `opportunistic` (default) or `enforced`.
     * 
     */
    public Optional<Output<DomainTLS>> tls() {
        return Optional.ofNullable(this.tls);
    }

    /**
     * Custom subdomain used for open/click tracking links.
     * 
     */
    @Import(name="trackingSubdomain")
    private @Nullable Output<String> trackingSubdomain;

    /**
     * @return Custom subdomain used for open/click tracking links.
     * 
     */
    public Optional<Output<String>> trackingSubdomain() {
        return Optional.ofNullable(this.trackingSubdomain);
    }

    private DomainArgs() {}

    private DomainArgs(DomainArgs $) {
        this.capabilities = $.capabilities;
        this.clickTracking = $.clickTracking;
        this.customReturnPath = $.customReturnPath;
        this.name = $.name;
        this.openTracking = $.openTracking;
        this.region = $.region;
        this.tls = $.tls;
        this.trackingSubdomain = $.trackingSubdomain;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainArgs $;

        public Builder() {
            $ = new DomainArgs();
        }

        public Builder(DomainArgs defaults) {
            $ = new DomainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param capabilities Enable `sending` and/or `receiving` for this domain.
         * 
         * @return builder
         * 
         */
        public Builder capabilities(@Nullable Output<DomainCapabilitiesArgs> capabilities) {
            $.capabilities = capabilities;
            return this;
        }

        /**
         * @param capabilities Enable `sending` and/or `receiving` for this domain.
         * 
         * @return builder
         * 
         */
        public Builder capabilities(DomainCapabilitiesArgs capabilities) {
            return capabilities(Output.of(capabilities));
        }

        /**
         * @param clickTracking Track link clicks in HTML emails. Requires a verified tracking subdomain.
         * 
         * @return builder
         * 
         */
        public Builder clickTracking(@Nullable Output<Boolean> clickTracking) {
            $.clickTracking = clickTracking;
            return this;
        }

        /**
         * @param clickTracking Track link clicks in HTML emails. Requires a verified tracking subdomain.
         * 
         * @return builder
         * 
         */
        public Builder clickTracking(Boolean clickTracking) {
            return clickTracking(Output.of(clickTracking));
        }

        /**
         * @param customReturnPath The subdomain used for the Return-Path address. Defaults to `send`.
         * 
         * @return builder
         * 
         */
        public Builder customReturnPath(@Nullable Output<String> customReturnPath) {
            $.customReturnPath = customReturnPath;
            return this;
        }

        /**
         * @param customReturnPath The subdomain used for the Return-Path address. Defaults to `send`.
         * 
         * @return builder
         * 
         */
        public Builder customReturnPath(String customReturnPath) {
            return customReturnPath(Output.of(customReturnPath));
        }

        /**
         * @param name The domain name, e.g. `example.com`.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The domain name, e.g. `example.com`.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param openTracking Track email open rates. Requires a verified tracking subdomain.
         * 
         * @return builder
         * 
         */
        public Builder openTracking(@Nullable Output<Boolean> openTracking) {
            $.openTracking = openTracking;
            return this;
        }

        /**
         * @param openTracking Track email open rates. Requires a verified tracking subdomain.
         * 
         * @return builder
         * 
         */
        public Builder openTracking(Boolean openTracking) {
            return openTracking(Output.of(openTracking));
        }

        /**
         * @param region The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
         * 
         * @return builder
         * 
         */
        public Builder region(@Nullable Output<DomainRegion> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
         * 
         * @return builder
         * 
         */
        public Builder region(DomainRegion region) {
            return region(Output.of(region));
        }

        /**
         * @param tls Connection encryption: `opportunistic` (default) or `enforced`.
         * 
         * @return builder
         * 
         */
        public Builder tls(@Nullable Output<DomainTLS> tls) {
            $.tls = tls;
            return this;
        }

        /**
         * @param tls Connection encryption: `opportunistic` (default) or `enforced`.
         * 
         * @return builder
         * 
         */
        public Builder tls(DomainTLS tls) {
            return tls(Output.of(tls));
        }

        /**
         * @param trackingSubdomain Custom subdomain used for open/click tracking links.
         * 
         * @return builder
         * 
         */
        public Builder trackingSubdomain(@Nullable Output<String> trackingSubdomain) {
            $.trackingSubdomain = trackingSubdomain;
            return this;
        }

        /**
         * @param trackingSubdomain Custom subdomain used for open/click tracking links.
         * 
         * @return builder
         * 
         */
        public Builder trackingSubdomain(String trackingSubdomain) {
            return trackingSubdomain(Output.of(trackingSubdomain));
        }

        public DomainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("DomainArgs", "name");
            }
            return $;
        }
    }

}
