// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainVerificationArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainVerificationArgs Empty = new DomainVerificationArgs();

    /**
     * The ID of the domain to verify.
     * 
     */
    @Import(name="domainId", required=true)
    private Output<String> domainId;

    /**
     * @return The ID of the domain to verify.
     * 
     */
    public Output<String> domainId() {
        return this.domainId;
    }

    /**
     * How long to wait for verification before failing. Defaults to 900 seconds.
     * 
     */
    @Import(name="timeoutSeconds")
    private @Nullable Output<Integer> timeoutSeconds;

    /**
     * @return How long to wait for verification before failing. Defaults to 900 seconds.
     * 
     */
    public Optional<Output<Integer>> timeoutSeconds() {
        return Optional.ofNullable(this.timeoutSeconds);
    }

    private DomainVerificationArgs() {}

    private DomainVerificationArgs(DomainVerificationArgs $) {
        this.domainId = $.domainId;
        this.timeoutSeconds = $.timeoutSeconds;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainVerificationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainVerificationArgs $;

        public Builder() {
            $ = new DomainVerificationArgs();
        }

        public Builder(DomainVerificationArgs defaults) {
            $ = new DomainVerificationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param domainId The ID of the domain to verify.
         * 
         * @return builder
         * 
         */
        public Builder domainId(Output<String> domainId) {
            $.domainId = domainId;
            return this;
        }

        /**
         * @param domainId The ID of the domain to verify.
         * 
         * @return builder
         * 
         */
        public Builder domainId(String domainId) {
            return domainId(Output.of(domainId));
        }

        /**
         * @param timeoutSeconds How long to wait for verification before failing. Defaults to 900 seconds.
         * 
         * @return builder
         * 
         */
        public Builder timeoutSeconds(@Nullable Output<Integer> timeoutSeconds) {
            $.timeoutSeconds = timeoutSeconds;
            return this;
        }

        /**
         * @param timeoutSeconds How long to wait for verification before failing. Defaults to 900 seconds.
         * 
         * @return builder
         * 
         */
        public Builder timeoutSeconds(Integer timeoutSeconds) {
            return timeoutSeconds(Output.of(timeoutSeconds));
        }

        public DomainVerificationArgs build() {
            if ($.domainId == null) {
                throw new MissingRequiredPropertyException("DomainVerificationArgs", "domainId");
            }
            return $;
        }
    }

}
