// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend;

import com.iwahbe.resend.DomainArgs;
import com.iwahbe.resend.Utilities;
import com.iwahbe.resend.enums.DomainRegion;
import com.iwahbe.resend.enums.DomainTLS;
import com.iwahbe.resend.outputs.DomainCapabilities;
import com.iwahbe.resend.outputs.DomainRecord;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A domain registered with Resend for sending (and optionally receiving) email. The `records` output contains the DNS records that must be created before the domain can be verified.
 * 
 */
@ResourceType(type="resend:index:Domain")
public class Domain extends com.pulumi.resources.CustomResource {
    /**
     * Enable `sending` and/or `receiving` for this domain.
     * 
     */
    @Export(name="capabilities", refs={DomainCapabilities.class}, tree="[0]")
    private Output</* @Nullable */ DomainCapabilities> capabilities;

    /**
     * @return Enable `sending` and/or `receiving` for this domain.
     * 
     */
    public Output<Optional<DomainCapabilities>> capabilities() {
        return Codegen.optional(this.capabilities);
    }
    /**
     * Track link clicks in HTML emails. Requires a verified tracking subdomain.
     * 
     */
    @Export(name="clickTracking", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> clickTracking;

    /**
     * @return Track link clicks in HTML emails. Requires a verified tracking subdomain.
     * 
     */
    public Output<Optional<Boolean>> clickTracking() {
        return Codegen.optional(this.clickTracking);
    }
    @Export(name="createdAt", refs={String.class}, tree="[0]")
    private Output<String> createdAt;

    public Output<String> createdAt() {
        return this.createdAt;
    }
    /**
     * The subdomain used for the Return-Path address. Defaults to `send`.
     * 
     */
    @Export(name="customReturnPath", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> customReturnPath;

    /**
     * @return The subdomain used for the Return-Path address. Defaults to `send`.
     * 
     */
    public Output<Optional<String>> customReturnPath() {
        return Codegen.optional(this.customReturnPath);
    }
    /**
     * The domain name, e.g. `example.com`.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The domain name, e.g. `example.com`.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Track email open rates. Requires a verified tracking subdomain.
     * 
     */
    @Export(name="openTracking", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> openTracking;

    /**
     * @return Track email open rates. Requires a verified tracking subdomain.
     * 
     */
    public Output<Optional<Boolean>> openTracking() {
        return Codegen.optional(this.openTracking);
    }
    /**
     * The DNS records to create for this domain.
     * 
     */
    @Export(name="records", refs={List.class,DomainRecord.class}, tree="[0,1]")
    private Output<List<DomainRecord>> records;

    /**
     * @return The DNS records to create for this domain.
     * 
     */
    public Output<List<DomainRecord>> records() {
        return this.records;
    }
    /**
     * The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
     * 
     */
    @Export(name="region", refs={DomainRegion.class}, tree="[0]")
    private Output</* @Nullable */ DomainRegion> region;

    /**
     * @return The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
     * 
     */
    public Output<Optional<DomainRegion>> region() {
        return Codegen.optional(this.region);
    }
    /**
     * The verification status of the domain.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return The verification status of the domain.
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * Connection encryption: `opportunistic` (default) or `enforced`.
     * 
     */
    @Export(name="tls", refs={DomainTLS.class}, tree="[0]")
    private Output</* @Nullable */ DomainTLS> tls;

    /**
     * @return Connection encryption: `opportunistic` (default) or `enforced`.
     * 
     */
    public Output<Optional<DomainTLS>> tls() {
        return Codegen.optional(this.tls);
    }
    /**
     * Custom subdomain used for open/click tracking links.
     * 
     */
    @Export(name="trackingSubdomain", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> trackingSubdomain;

    /**
     * @return Custom subdomain used for open/click tracking links.
     * 
     */
    public Output<Optional<String>> trackingSubdomain() {
        return Codegen.optional(this.trackingSubdomain);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Domain(java.lang.String name) {
        this(name, DomainArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Domain(java.lang.String name, DomainArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Domain(java.lang.String name, DomainArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("resend:index:Domain", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Domain(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("resend:index:Domain", name, null, makeResourceOptions(options, id), false);
    }

    private static DomainArgs makeArgs(DomainArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? DomainArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/iwahbe/pulumi-resend")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Domain get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Domain(name, id, options);
    }
}
