// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend;

import com.iwahbe.resend.DomainVerificationArgs;
import com.iwahbe.resend.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Triggers verification of a Resend domain and waits until the domain&#39;s DNS records have been verified. Create this resource after the domain&#39;s DNS records (from the `Domain` resource&#39;s `records` output) have been published.
 * 
 */
@ResourceType(type="resend:index:DomainVerification")
public class DomainVerification extends com.pulumi.resources.CustomResource {
    /**
     * The ID of the domain to verify.
     * 
     */
    @Export(name="domainId", refs={String.class}, tree="[0]")
    private Output<String> domainId;

    /**
     * @return The ID of the domain to verify.
     * 
     */
    public Output<String> domainId() {
        return this.domainId;
    }
    /**
     * The verification status of the domain.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return The verification status of the domain.
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * How long to wait for verification before failing. Defaults to 900 seconds.
     * 
     */
    @Export(name="timeoutSeconds", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> timeoutSeconds;

    /**
     * @return How long to wait for verification before failing. Defaults to 900 seconds.
     * 
     */
    public Output<Optional<Integer>> timeoutSeconds() {
        return Codegen.optional(this.timeoutSeconds);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DomainVerification(java.lang.String name) {
        this(name, DomainVerificationArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DomainVerification(java.lang.String name, DomainVerificationArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DomainVerification(java.lang.String name, DomainVerificationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("resend:index:DomainVerification", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private DomainVerification(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("resend:index:DomainVerification", name, null, makeResourceOptions(options, id), false);
    }

    private static DomainVerificationArgs makeArgs(DomainVerificationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? DomainVerificationArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/iwahbe/pulumi-resend")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DomainVerification get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DomainVerification(name, id, options);
    }
}
