// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class SegmentArgs extends com.pulumi.resources.ResourceArgs {

    public static final SegmentArgs Empty = new SegmentArgs();

    /**
     * The segment name.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The segment name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private SegmentArgs() {}

    private SegmentArgs(SegmentArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SegmentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SegmentArgs $;

        public Builder() {
            $ = new SegmentArgs();
        }

        public Builder(SegmentArgs defaults) {
            $ = new SegmentArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The segment name.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The segment name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public SegmentArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("SegmentArgs", "name");
            }
            return $;
        }
    }

}
