// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend;

import com.iwahbe.resend.enums.TopicDefaultSubscription;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TopicArgs extends com.pulumi.resources.ResourceArgs {

    public static final TopicArgs Empty = new TopicArgs();

    /**
     * The default subscription preference for new contacts, either `opt_in` or `opt_out`. Resend does not allow this value to change after creation, so changes replace the topic.
     * 
     */
    @Import(name="defaultSubscription", required=true)
    private Output<TopicDefaultSubscription> defaultSubscription;

    /**
     * @return The default subscription preference for new contacts, either `opt_in` or `opt_out`. Resend does not allow this value to change after creation, so changes replace the topic.
     * 
     */
    public Output<TopicDefaultSubscription> defaultSubscription() {
        return this.defaultSubscription;
    }

    /**
     * An optional topic description. Non-empty values are sent to Resend on create and update. Because resend-go v4.2.0 omits empty `description` values from update requests, clearing an existing description replaces the topic.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return An optional topic description. Non-empty values are sent to Resend on create and update. Because resend-go v4.2.0 omits empty `description` values from update requests, clearing an existing description replaces the topic.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The topic name.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The topic name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private TopicArgs() {}

    private TopicArgs(TopicArgs $) {
        this.defaultSubscription = $.defaultSubscription;
        this.description = $.description;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TopicArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TopicArgs $;

        public Builder() {
            $ = new TopicArgs();
        }

        public Builder(TopicArgs defaults) {
            $ = new TopicArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param defaultSubscription The default subscription preference for new contacts, either `opt_in` or `opt_out`. Resend does not allow this value to change after creation, so changes replace the topic.
         * 
         * @return builder
         * 
         */
        public Builder defaultSubscription(Output<TopicDefaultSubscription> defaultSubscription) {
            $.defaultSubscription = defaultSubscription;
            return this;
        }

        /**
         * @param defaultSubscription The default subscription preference for new contacts, either `opt_in` or `opt_out`. Resend does not allow this value to change after creation, so changes replace the topic.
         * 
         * @return builder
         * 
         */
        public Builder defaultSubscription(TopicDefaultSubscription defaultSubscription) {
            return defaultSubscription(Output.of(defaultSubscription));
        }

        /**
         * @param description An optional topic description. Non-empty values are sent to Resend on create and update. Because resend-go v4.2.0 omits empty `description` values from update requests, clearing an existing description replaces the topic.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description An optional topic description. Non-empty values are sent to Resend on create and update. Because resend-go v4.2.0 omits empty `description` values from update requests, clearing an existing description replaces the topic.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param name The topic name.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The topic name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public TopicArgs build() {
            if ($.defaultSubscription == null) {
                throw new MissingRequiredPropertyException("TopicArgs", "defaultSubscription");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("TopicArgs", "name");
            }
            return $;
        }
    }

}
