// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend;

import com.iwahbe.resend.TopicArgs;
import com.iwahbe.resend.Utilities;
import com.iwahbe.resend.enums.TopicDefaultSubscription;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A Resend broadcast topic used to manage contact subscription preferences.
 * 
 */
@ResourceType(type="resend:index:Topic")
public class Topic extends com.pulumi.resources.CustomResource {
    /**
     * The timestamp when Resend created the topic, as returned by the Resend API `created_at` string in `YYYY-MM-DD HH:MM:SS.ffffff+00` format (for example, `2023-04-08 00:11:13.110779+00`).
     * 
     */
    @Export(name="createdAt", refs={String.class}, tree="[0]")
    private Output<String> createdAt;

    /**
     * @return The timestamp when Resend created the topic, as returned by the Resend API `created_at` string in `YYYY-MM-DD HH:MM:SS.ffffff+00` format (for example, `2023-04-08 00:11:13.110779+00`).
     * 
     */
    public Output<String> createdAt() {
        return this.createdAt;
    }
    /**
     * The default subscription preference for new contacts, either `opt_in` or `opt_out`. Resend does not allow this value to change after creation, so changes replace the topic.
     * 
     */
    @Export(name="defaultSubscription", refs={TopicDefaultSubscription.class}, tree="[0]")
    private Output<TopicDefaultSubscription> defaultSubscription;

    /**
     * @return The default subscription preference for new contacts, either `opt_in` or `opt_out`. Resend does not allow this value to change after creation, so changes replace the topic.
     * 
     */
    public Output<TopicDefaultSubscription> defaultSubscription() {
        return this.defaultSubscription;
    }
    /**
     * An optional topic description. Non-empty values are sent to Resend on create and update. Because resend-go v4.2.0 omits empty `description` values from update requests, clearing an existing description replaces the topic.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return An optional topic description. Non-empty values are sent to Resend on create and update. Because resend-go v4.2.0 omits empty `description` values from update requests, clearing an existing description replaces the topic.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * The topic name.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The topic name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Topic(java.lang.String name) {
        this(name, TopicArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Topic(java.lang.String name, TopicArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Topic(java.lang.String name, TopicArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("resend:index:Topic", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Topic(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("resend:index:Topic", name, null, makeResourceOptions(options, id), false);
    }

    private static TopicArgs makeArgs(TopicArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? TopicArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/iwahbe/pulumi-resend")
            .replaceOnChanges(List.of(
                "defaultSubscription"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Topic get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Topic(name, id, options);
    }
}
