// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend;

import com.iwahbe.resend.Utilities;
import com.iwahbe.resend.WebhookArgs;
import com.iwahbe.resend.enums.WebhookEvent;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * A Resend webhook that delivers events to an HTTPS endpoint. If Resend omits the `signingSecret` during import or read, the provider returns an empty secret for imports and preserves any existing state value during refreshes.
 * 
 */
@ResourceType(type="resend:index:Webhook")
public class Webhook extends com.pulumi.resources.CustomResource {
    @Export(name="createdAt", refs={String.class}, tree="[0]")
    private Output<String> createdAt;

    public Output<String> createdAt() {
        return this.createdAt;
    }
    /**
     * The HTTPS URL events are delivered to.
     * 
     */
    @Export(name="endpoint", refs={String.class}, tree="[0]")
    private Output<String> endpoint;

    /**
     * @return The HTTPS URL events are delivered to.
     * 
     */
    public Output<String> endpoint() {
        return this.endpoint;
    }
    /**
     * The event types to subscribe to, e.g. `email.sent` or `domain.updated`.
     * 
     */
    @Export(name="events", refs={List.class,WebhookEvent.class}, tree="[0,1]")
    private Output<List<WebhookEvent>> events;

    /**
     * @return The event types to subscribe to, e.g. `email.sent` or `domain.updated`.
     * 
     */
    public Output<List<WebhookEvent>> events() {
        return this.events;
    }
    /**
     * The secret used to verify webhook payload signatures; may be empty after import if Resend does not return it.
     * 
     */
    @Export(name="signingSecret", refs={String.class}, tree="[0]")
    private Output<String> signingSecret;

    /**
     * @return The secret used to verify webhook payload signatures; may be empty after import if Resend does not return it.
     * 
     */
    public Output<String> signingSecret() {
        return this.signingSecret;
    }
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    public Output<String> status() {
        return this.status;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Webhook(java.lang.String name) {
        this(name, WebhookArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Webhook(java.lang.String name, WebhookArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Webhook(java.lang.String name, WebhookArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("resend:index:Webhook", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Webhook(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("resend:index:Webhook", name, null, makeResourceOptions(options, id), false);
    }

    private static WebhookArgs makeArgs(WebhookArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? WebhookArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/iwahbe/pulumi-resend")
            .additionalSecretOutputs(List.of(
                "signingSecret"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Webhook get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Webhook(name, id, options);
    }
}
