// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.iwahbe.resend;

import com.iwahbe.resend.enums.WebhookEvent;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class WebhookArgs extends com.pulumi.resources.ResourceArgs {

    public static final WebhookArgs Empty = new WebhookArgs();

    /**
     * The HTTPS URL events are delivered to.
     * 
     */
    @Import(name="endpoint", required=true)
    private Output<String> endpoint;

    /**
     * @return The HTTPS URL events are delivered to.
     * 
     */
    public Output<String> endpoint() {
        return this.endpoint;
    }

    /**
     * The event types to subscribe to, e.g. `email.sent` or `domain.updated`.
     * 
     */
    @Import(name="events", required=true)
    private Output<List<WebhookEvent>> events;

    /**
     * @return The event types to subscribe to, e.g. `email.sent` or `domain.updated`.
     * 
     */
    public Output<List<WebhookEvent>> events() {
        return this.events;
    }

    private WebhookArgs() {}

    private WebhookArgs(WebhookArgs $) {
        this.endpoint = $.endpoint;
        this.events = $.events;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(WebhookArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private WebhookArgs $;

        public Builder() {
            $ = new WebhookArgs();
        }

        public Builder(WebhookArgs defaults) {
            $ = new WebhookArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param endpoint The HTTPS URL events are delivered to.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(Output<String> endpoint) {
            $.endpoint = endpoint;
            return this;
        }

        /**
         * @param endpoint The HTTPS URL events are delivered to.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(String endpoint) {
            return endpoint(Output.of(endpoint));
        }

        /**
         * @param events The event types to subscribe to, e.g. `email.sent` or `domain.updated`.
         * 
         * @return builder
         * 
         */
        public Builder events(Output<List<WebhookEvent>> events) {
            $.events = events;
            return this;
        }

        /**
         * @param events The event types to subscribe to, e.g. `email.sent` or `domain.updated`.
         * 
         * @return builder
         * 
         */
        public Builder events(List<WebhookEvent> events) {
            return events(Output.of(events));
        }

        /**
         * @param events The event types to subscribe to, e.g. `email.sent` or `domain.updated`.
         * 
         * @return builder
         * 
         */
        public Builder events(WebhookEvent... events) {
            return events(List.of(events));
        }

        public WebhookArgs build() {
            if ($.endpoint == null) {
                throw new MissingRequiredPropertyException("WebhookArgs", "endpoint");
            }
            if ($.events == null) {
                throw new MissingRequiredPropertyException("WebhookArgs", "events");
            }
            return $;
        }
    }

}
