// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A Resend custom contact property definition.
 */
export class ContactProperty extends pulumi.CustomResource {
    /**
     * Get an existing ContactProperty resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ContactProperty {
        return new ContactProperty(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'resend:index:ContactProperty';

    /**
     * Returns true if the given object is an instance of ContactProperty.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ContactProperty {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ContactProperty.__pulumiType;
    }

    /**
     * The timestamp when Resend created the contact property, as returned by the Resend API `created_at` string.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
     */
    declare public readonly fallbackValue: pulumi.Output<any | undefined>;
    /**
     * The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
     */
    declare public readonly key: pulumi.Output<string>;
    /**
     * The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
     */
    declare public readonly type: pulumi.Output<enums.ContactPropertyType>;

    /**
     * Create a ContactProperty resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ContactPropertyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["fallbackValue"] = args?.fallbackValue;
            resourceInputs["key"] = args?.key;
            resourceInputs["type"] = args?.type;
            resourceInputs["createdAt"] = undefined /*out*/;
        } else {
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["fallbackValue"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["key", "type"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(ContactProperty.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ContactProperty resource.
 */
export interface ContactPropertyArgs {
    /**
     * Optional fallback value used when a contact does not have this property set. Values must match `type` (`string` or `number`). Fallback changes, including clearing a previously non-null fallback, update in place.
     */
    fallbackValue?: any | undefined;
    /**
     * The contact property key. Resend allows up to 50 alphanumeric or underscore characters. The key cannot be changed after creation, so changes replace the resource.
     */
    key: pulumi.Input<string>;
    /**
     * The contact property type, either `string` or `number`. The type cannot be changed after creation, so changes replace the resource.
     */
    type: pulumi.Input<enums.ContactPropertyType>;
}
