// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A domain registered with Resend for sending (and optionally receiving) email. The `records` output contains the DNS records that must be created before the domain can be verified.
 */
export class Domain extends pulumi.CustomResource {
    /**
     * Get an existing Domain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Domain {
        return new Domain(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'resend:index:Domain';

    /**
     * Returns true if the given object is an instance of Domain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Domain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Domain.__pulumiType;
    }

    /**
     * Enable `sending` and/or `receiving` for this domain.
     */
    declare public readonly capabilities: pulumi.Output<outputs.DomainCapabilities | undefined>;
    /**
     * Track link clicks in HTML emails. Requires a verified tracking subdomain.
     */
    declare public readonly clickTracking: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The subdomain used for the Return-Path address. Defaults to `send`.
     */
    declare public readonly customReturnPath: pulumi.Output<string | undefined>;
    /**
     * The domain name, e.g. `example.com`.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Track email open rates. Requires a verified tracking subdomain.
     */
    declare public readonly openTracking: pulumi.Output<boolean | undefined>;
    /**
     * The DNS records to create for this domain.
     */
    declare public /*out*/ readonly records: pulumi.Output<outputs.DomainRecord[]>;
    /**
     * The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
     */
    declare public readonly region: pulumi.Output<enums.DomainRegion | undefined>;
    /**
     * The verification status of the domain.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Connection encryption: `opportunistic` (default) or `enforced`.
     */
    declare public readonly tls: pulumi.Output<enums.DomainTLS | undefined>;
    /**
     * Custom subdomain used for open/click tracking links.
     */
    declare public readonly trackingSubdomain: pulumi.Output<string | undefined>;

    /**
     * Create a Domain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["capabilities"] = args?.capabilities;
            resourceInputs["clickTracking"] = args?.clickTracking;
            resourceInputs["customReturnPath"] = args?.customReturnPath;
            resourceInputs["name"] = args?.name;
            resourceInputs["openTracking"] = args?.openTracking;
            resourceInputs["region"] = args?.region;
            resourceInputs["tls"] = args?.tls;
            resourceInputs["trackingSubdomain"] = args?.trackingSubdomain;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["records"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        } else {
            resourceInputs["capabilities"] = undefined /*out*/;
            resourceInputs["clickTracking"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["customReturnPath"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["openTracking"] = undefined /*out*/;
            resourceInputs["records"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["tls"] = undefined /*out*/;
            resourceInputs["trackingSubdomain"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Domain.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Domain resource.
 */
export interface DomainArgs {
    /**
     * Enable `sending` and/or `receiving` for this domain.
     */
    capabilities?: pulumi.Input<inputs.DomainCapabilitiesArgs | undefined>;
    /**
     * Track link clicks in HTML emails. Requires a verified tracking subdomain.
     */
    clickTracking?: pulumi.Input<boolean | undefined>;
    /**
     * The subdomain used for the Return-Path address. Defaults to `send`.
     */
    customReturnPath?: pulumi.Input<string | undefined>;
    /**
     * The domain name, e.g. `example.com`.
     */
    name: pulumi.Input<string>;
    /**
     * Track email open rates. Requires a verified tracking subdomain.
     */
    openTracking?: pulumi.Input<boolean | undefined>;
    /**
     * The region emails are sent from: `us-east-1` (default), `eu-west-1`, `sa-east-1`, or `ap-northeast-1`.
     */
    region?: pulumi.Input<enums.DomainRegion | undefined>;
    /**
     * Connection encryption: `opportunistic` (default) or `enforced`.
     */
    tls?: pulumi.Input<enums.DomainTLS | undefined>;
    /**
     * Custom subdomain used for open/click tracking links.
     */
    trackingSubdomain?: pulumi.Input<string | undefined>;
}
